// Q33a — generated by GenDB
#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <string>
#include <string_view>
#include <vector>
#include <fcntl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>
#include <fstream>
#include <omp.h>

#include "timing_utils.h"
#include "cli_params.h"

static void* mmap_file(const std::string& path, size_t* out_size = nullptr) {
    int fd = open(path.c_str(), O_RDONLY);
    if (fd < 0) { std::fprintf(stderr, "open failed: %s\n", path.c_str()); std::exit(1); }
    struct stat st; fstat(fd, &st);
    void* p = mmap(nullptr, st.st_size, PROT_READ, MAP_SHARED, fd, 0);
    if (p == MAP_FAILED) { std::fprintf(stderr, "mmap failed: %s\n", path.c_str()); std::exit(1); }
    close(fd);
    if (out_size) *out_size = st.st_size;
    return p;
}

static inline std::string_view sv_at(const uint64_t* off, const char* dat, uint64_t r) {
    return std::string_view(dat + off[r], off[r+1] - off[r]);
}

int main(int argc, char* argv[]) {
    GENDB_PHASE("total");
    if (argc < 3) { std::fprintf(stderr, "usage: %s <gendb_dir> <results_dir> [--params...]\n", argv[0]); return 1; }
    std::string gendb_dir = argv[1];
    std::string results_dir = argv[2];

    // Parse CLI params
    int64_t pyear_lo = gendb::parse_int_arg(argc, argv, "--production_year_lower", 2005);
    int64_t pyear_hi = gendb::parse_int_arg(argc, argv, "--production_year_upper", 2008);
    double  info_upper = gendb::parse_double_arg(argc, argv, "--info_upper", 3.0);
    std::string info_eq      = gendb::parse_string_arg(argc, argv, "--info_eq",      std::string("rating"));
    std::string info_eq_2    = gendb::parse_string_arg(argc, argv, "--info_eq_2",    std::string("rating"));
    std::string country_code = gendb::parse_string_arg(argc, argv, "--country_code_eq", std::string("[us]"));

    // Format info_upper as "%.1f" (default 3.0) — comparison is lexicographic on varlen text
    char info_upper_buf[32];
    std::snprintf(info_upper_buf, sizeof(info_upper_buf), "%.1f", info_upper);
    std::string info_upper_str(info_upper_buf);

    // ---- Load (mmap) all needed columns/indexes ----
    void* p_data;
    size_t sz;

    // info_type
    const int32_t* it_id;
    const uint64_t* it_info_off;
    const char* it_info_dat;
    uint64_t it_rows;
    {
        it_id = (const int32_t*)mmap_file(gendb_dir + "/info_type/id.bin", &sz);
        it_rows = sz / 4;
        it_info_off = (const uint64_t*)mmap_file(gendb_dir + "/info_type/info.offsets.bin");
        it_info_dat = (const char*)mmap_file(gendb_dir + "/info_type/info.data.bin");
    }

    // kind_type
    const int32_t* kt_id;
    const uint64_t* kt_kind_off;
    const char* kt_kind_dat;
    uint64_t kt_rows;
    {
        kt_id = (const int32_t*)mmap_file(gendb_dir + "/kind_type/id.bin", &sz);
        kt_rows = sz / 4;
        kt_kind_off = (const uint64_t*)mmap_file(gendb_dir + "/kind_type/kind.offsets.bin");
        kt_kind_dat = (const char*)mmap_file(gendb_dir + "/kind_type/kind.data.bin");
    }

    // link_type
    const int32_t* lt_id;
    const uint64_t* lt_link_off;
    const char* lt_link_dat;
    uint64_t lt_rows;
    {
        lt_id = (const int32_t*)mmap_file(gendb_dir + "/link_type/id.bin", &sz);
        lt_rows = sz / 4;
        lt_link_off = (const uint64_t*)mmap_file(gendb_dir + "/link_type/link.offsets.bin");
        lt_link_dat = (const char*)mmap_file(gendb_dir + "/link_type/link.data.bin");
    }

    // company_name
    const int32_t* cn_id;
    const uint64_t* cn_cc_off;
    const char* cn_cc_dat;
    const uint64_t* cn_name_off;
    const char* cn_name_dat;
    uint64_t cn_rows;
    {
        cn_id = (const int32_t*)mmap_file(gendb_dir + "/company_name/id.bin", &sz);
        cn_rows = sz / 4;
        cn_cc_off = (const uint64_t*)mmap_file(gendb_dir + "/company_name/country_code.offsets.bin");
        cn_cc_dat = (const char*)mmap_file(gendb_dir + "/company_name/country_code.data.bin");
        cn_name_off = (const uint64_t*)mmap_file(gendb_dir + "/company_name/name.offsets.bin");
        cn_name_dat = (const char*)mmap_file(gendb_dir + "/company_name/name.data.bin");
    }
    const int32_t* cn_id_pos = (const int32_t*)mmap_file(gendb_dir + "/indexes/company_name__id__pos.bin", &sz);
    size_t cn_id_pos_n = sz / 4;

    // title
    const int32_t* t_kind_id = (const int32_t*)mmap_file(gendb_dir + "/title/kind_id.bin");
    const int32_t* t_year    = (const int32_t*)mmap_file(gendb_dir + "/title/production_year.bin");
    const uint64_t* t_title_off = (const uint64_t*)mmap_file(gendb_dir + "/title/title.offsets.bin");
    const char* t_title_dat = (const char*)mmap_file(gendb_dir + "/title/title.data.bin");
    const int32_t* t_id_pos = (const int32_t*)mmap_file(gendb_dir + "/indexes/title__id__pos.bin", &sz);
    size_t t_id_pos_n = sz / 4;

    // movie_link
    const int32_t* ml_movie_id        = (const int32_t*)mmap_file(gendb_dir + "/movie_link/movie_id.bin");
    const int32_t* ml_linked_movie_id = (const int32_t*)mmap_file(gendb_dir + "/movie_link/linked_movie_id.bin");
    const uint64_t* ml_lt_off = (const uint64_t*)mmap_file(gendb_dir + "/indexes/movie_link__link_type_id__offsets.bin", &sz);
    size_t ml_lt_off_n = sz / 8;
    const int32_t* ml_lt_rowids = (const int32_t*)mmap_file(gendb_dir + "/indexes/movie_link__link_type_id__rowids.bin");

    // movie_info_idx
    const int32_t* mii_info_type_id = (const int32_t*)mmap_file(gendb_dir + "/movie_info_idx/info_type_id.bin");
    const uint64_t* mii_info_off    = (const uint64_t*)mmap_file(gendb_dir + "/movie_info_idx/info.offsets.bin");
    const char* mii_info_dat        = (const char*)mmap_file(gendb_dir + "/movie_info_idx/info.data.bin");
    const uint64_t* mii_mid_off     = (const uint64_t*)mmap_file(gendb_dir + "/indexes/movie_info_idx__movie_id__offsets.bin", &sz);
    size_t mii_mid_off_n = sz / 8;

    // movie_companies
    const int32_t* mc_company_id = (const int32_t*)mmap_file(gendb_dir + "/movie_companies/company_id.bin");
    const uint64_t* mc_mid_off   = (const uint64_t*)mmap_file(gendb_dir + "/indexes/movie_companies__movie_id__offsets.bin", &sz);
    size_t mc_mid_off_n = sz / 8;

    (void)p_data; (void)cn_id_pos_n; (void)t_id_pos_n; (void)ml_lt_off_n; (void)mii_mid_off_n; (void)mc_mid_off_n;

    // ---- Resolve dimension literals ----
    int32_t rating_info_type_id = -1;
    for (uint64_t r = 0; r < it_rows; ++r) {
        if (sv_at(it_info_off, it_info_dat, r) == info_eq) { rating_info_type_id = it_id[r]; break; }
    }
    int32_t tv_series_kind_id = -1;
    for (uint64_t r = 0; r < kt_rows; ++r) {
        if (sv_at(kt_kind_off, kt_kind_dat, r) == std::string_view("tv series")) {
            tv_series_kind_id = kt_id[r]; break;
        }
    }
    std::vector<int32_t> lt_ids;
    for (uint64_t r = 0; r < lt_rows; ++r) {
        auto s = sv_at(lt_link_off, lt_link_dat, r);
        if (s == "sequel" || s == "follows" || s == "followed by") lt_ids.push_back(lt_id[r]);
    }
    (void)info_eq_2; // not separately used (both rating)

    if (rating_info_type_id < 0 || tv_series_kind_id < 0 || lt_ids.empty()) {
        // Empty output
        std::ofstream out(results_dir + "/Q33a.csv");
        out << "first_company,second_company,first_rating,second_rating,first_movie,second_movie\n";
        return 0;
    }

    // ---- Build us_company bitset ----
    std::vector<uint8_t> us_company;
    {
        GENDB_PHASE("build_us_bitset");
        int32_t max_company_id = 0;
        for (uint64_t r = 0; r < cn_rows; ++r) if (cn_id[r] > max_company_id) max_company_id = cn_id[r];
        us_company.assign((size_t)max_company_id + 2, 0);
        for (uint64_t r = 0; r < cn_rows; ++r) {
            auto cc = sv_at(cn_cc_off, cn_cc_dat, r);
            if (cc == country_code) us_company[(size_t)cn_id[r]] = 1;
        }
    }
    size_t us_company_max = us_company.size();

    // ---- Collect candidate movie_link rowids ----
    std::vector<int32_t> ml_rows;
    {
        GENDB_PHASE("collect_ml_rows");
        for (int32_t lt : lt_ids) {
            if (lt < 0) continue;
            if ((size_t)lt + 1 >= ml_lt_off_n) continue;
            uint64_t lo = ml_lt_off[lt];
            uint64_t hi = ml_lt_off[lt + 1];
            for (uint64_t k = lo; k < hi; ++k) ml_rows.push_back(ml_lt_rowids[k]);
        }
    }

    // ---- Main probe loop, parallelized ----
    // Per-thread MIN aggregates
    int nthreads = omp_get_max_threads();
    struct Mins {
        std::string cn1, cn2, mi1, mi2, t1, t2;
        bool has = false;
    };
    std::vector<Mins> per_thread(nthreads);

    {
        GENDB_PHASE("main_scan");
        #pragma omp parallel
        {
            int tid = omp_get_thread_num();
            Mins& M = per_thread[tid];

            #pragma omp for schedule(static)
            for (size_t i = 0; i < ml_rows.size(); ++i) {
                int32_t mlr = ml_rows[i];
                int32_t t1_id = ml_movie_id[mlr];
                int32_t t2_id = ml_linked_movie_id[mlr];
                if (t1_id < 0 || t2_id < 0) continue;
                if ((size_t)t1_id >= t_id_pos_n || (size_t)t2_id >= t_id_pos_n) continue;
                int32_t t1_row = t_id_pos[t1_id];
                int32_t t2_row = t_id_pos[t2_id];
                if (t1_row < 0 || t2_row < 0) continue;
                if (t_kind_id[t1_row] != tv_series_kind_id) continue;
                if (t_kind_id[t2_row] != tv_series_kind_id) continue;
                int32_t y2 = t_year[t2_row];
                if (y2 < pyear_lo || y2 > pyear_hi) continue;

                // mi_idx1: movie_id = t1_id, info_type_id = rating
                if ((size_t)t1_id + 1 >= mii_mid_off_n) continue;
                uint64_t mi1_lo = mii_mid_off[t1_id];
                uint64_t mi1_hi = mii_mid_off[t1_id + 1];
                bool have_mi1 = false;
                std::string_view best_mi1;
                for (uint64_t r = mi1_lo; r < mi1_hi; ++r) {
                    if (mii_info_type_id[r] != rating_info_type_id) continue;
                    std::string_view v(mii_info_dat + mii_info_off[r], mii_info_off[r+1] - mii_info_off[r]);
                    if (!have_mi1 || v < best_mi1) { best_mi1 = v; have_mi1 = true; }
                }
                if (!have_mi1) continue;

                // mi_idx2: movie_id = t2_id, info_type_id = rating AND info < info_upper_str
                if ((size_t)t2_id + 1 >= mii_mid_off_n) continue;
                uint64_t mi2_lo = mii_mid_off[t2_id];
                uint64_t mi2_hi = mii_mid_off[t2_id + 1];
                bool have_mi2 = false;
                std::string_view best_mi2;
                for (uint64_t r = mi2_lo; r < mi2_hi; ++r) {
                    if (mii_info_type_id[r] != rating_info_type_id) continue;
                    std::string_view v(mii_info_dat + mii_info_off[r], mii_info_off[r+1] - mii_info_off[r]);
                    if (!(v < std::string_view(info_upper_str))) continue;
                    if (!have_mi2 || v < best_mi2) { best_mi2 = v; have_mi2 = true; }
                }
                if (!have_mi2) continue;

                // mc1: movie_id = t1_id, company is US
                if ((size_t)t1_id + 1 >= mc_mid_off_n) continue;
                uint64_t mc1_lo = mc_mid_off[t1_id];
                uint64_t mc1_hi = mc_mid_off[t1_id + 1];
                bool have_mc1 = false;
                std::string_view best_cn1;
                for (uint64_t r = mc1_lo; r < mc1_hi; ++r) {
                    int32_t cid = mc_company_id[r];
                    if (cid < 0 || (size_t)cid >= us_company_max) continue;
                    if (!us_company[(size_t)cid]) continue;
                    int32_t cn_row = cn_id_pos[cid];
                    if (cn_row < 0) continue;
                    std::string_view nm(cn_name_dat + cn_name_off[cn_row], cn_name_off[cn_row+1] - cn_name_off[cn_row]);
                    if (!have_mc1 || nm < best_cn1) { best_cn1 = nm; have_mc1 = true; }
                }
                if (!have_mc1) continue;

                // mc2: movie_id = t2_id, any company
                if ((size_t)t2_id + 1 >= mc_mid_off_n) continue;
                uint64_t mc2_lo = mc_mid_off[t2_id];
                uint64_t mc2_hi = mc_mid_off[t2_id + 1];
                bool have_mc2 = false;
                std::string_view best_cn2;
                for (uint64_t r = mc2_lo; r < mc2_hi; ++r) {
                    int32_t cid = mc_company_id[r];
                    if (cid < 0 || (size_t)cid >= cn_id_pos_n) continue;
                    int32_t cn_row = cn_id_pos[cid];
                    if (cn_row < 0) continue;
                    std::string_view nm(cn_name_dat + cn_name_off[cn_row], cn_name_off[cn_row+1] - cn_name_off[cn_row]);
                    if (!have_mc2 || nm < best_cn2) { best_cn2 = nm; have_mc2 = true; }
                }
                if (!have_mc2) continue;

                // t1.title and t2.title
                std::string_view t1_title(t_title_dat + t_title_off[t1_row], t_title_off[t1_row+1] - t_title_off[t1_row]);
                std::string_view t2_title(t_title_dat + t_title_off[t2_row], t_title_off[t2_row+1] - t_title_off[t2_row]);

                // Update per-thread mins
                auto upd = [](std::string& dst, std::string_view v, bool& has_field) {
                    if (!has_field || v < std::string_view(dst)) { dst.assign(v.data(), v.size()); has_field = true; }
                };
                (void)upd;
                if (!M.has) {
                    M.cn1.assign(best_cn1.data(), best_cn1.size());
                    M.cn2.assign(best_cn2.data(), best_cn2.size());
                    M.mi1.assign(best_mi1.data(), best_mi1.size());
                    M.mi2.assign(best_mi2.data(), best_mi2.size());
                    M.t1.assign(t1_title.data(), t1_title.size());
                    M.t2.assign(t2_title.data(), t2_title.size());
                    M.has = true;
                } else {
                    if (best_cn1 < std::string_view(M.cn1)) M.cn1.assign(best_cn1.data(), best_cn1.size());
                    if (best_cn2 < std::string_view(M.cn2)) M.cn2.assign(best_cn2.data(), best_cn2.size());
                    if (best_mi1 < std::string_view(M.mi1)) M.mi1.assign(best_mi1.data(), best_mi1.size());
                    if (best_mi2 < std::string_view(M.mi2)) M.mi2.assign(best_mi2.data(), best_mi2.size());
                    if (t1_title < std::string_view(M.t1)) M.t1.assign(t1_title.data(), t1_title.size());
                    if (t2_title < std::string_view(M.t2)) M.t2.assign(t2_title.data(), t2_title.size());
                }
            }
        }
    }

    // ---- Reduce ----
    Mins final_m;
    for (int t = 0; t < nthreads; ++t) {
        if (!per_thread[t].has) continue;
        if (!final_m.has) { final_m = per_thread[t]; continue; }
        const Mins& M = per_thread[t];
        if (M.cn1 < final_m.cn1) final_m.cn1 = M.cn1;
        if (M.cn2 < final_m.cn2) final_m.cn2 = M.cn2;
        if (M.mi1 < final_m.mi1) final_m.mi1 = M.mi1;
        if (M.mi2 < final_m.mi2) final_m.mi2 = M.mi2;
        if (M.t1 < final_m.t1) final_m.t1 = M.t1;
        if (M.t2 < final_m.t2) final_m.t2 = M.t2;
    }

    // ---- Output ----
    {
        GENDB_PHASE("output");
        std::ofstream out(results_dir + "/Q33a.csv");
        out << "first_company,second_company,first_rating,second_rating,first_movie,second_movie\n";
        if (final_m.has) {
            out << final_m.cn1 << ',' << final_m.cn2 << ','
                << final_m.mi1 << ',' << final_m.mi2 << ','
                << final_m.t1  << ',' << final_m.t2  << '\n';
        }
    }
    return 0;
}
