// Q16c - Generated by GenDB Code Generator
// Pipeline: keyword-driven CSR -> title episode filter -> mc US bitset -> ci -> aka_name
#include <cstdio>
#include <cstdint>
#include <cstring>
#include <climits>
#include <string>
#include <vector>
#include <filesystem>
#include <sys/stat.h>
#include "timing_utils.h"
#include "mmap_utils.h"
#include "cli_params.h"

using namespace gendb;

int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::fprintf(stderr, "Usage: %s <gendb_dir> <results_dir>\n", argv[0]);
        return 1;
    }
    std::string store = argv[1];
    std::string results_dir = argv[2];
    std::filesystem::create_directories(results_dir);

    GENDB_PHASE("total");

    // -------- Load all needed columns --------
    // keyword: keyword.off (uint64, 134171), keyword.dat
    // company_name: country_code.bin (int16, 234997), country_code.dict.off (uint64), country_code.dict.dat
    // title: episode_nr.bin (int32, 2528312), title.off (uint64, 2528313), title.dat
    // movie_keyword: keyword_id offsets/rowids CSR -> movie_id
    // movie_companies: company_id.bin, movie_id offsets-only
    // cast_info: person_id.bin, movie_id offsets-only
    // aka_name: name.off, name.dat, person_id offsets-only

    MmapColumn<uint64_t> kw_off, t_off, an_off, cn_cc_dict_off;
    MmapColumn<char>     kw_dat, t_dat, an_dat, cn_cc_dict_dat;
    MmapColumn<int16_t>  cn_cc;
    MmapColumn<int32_t>  t_ep;
    MmapColumn<int32_t>  mk_k_csr_off, mk_k_csr_row, mk_movie_id;
    MmapColumn<int32_t>  mc_movie_id_off, mc_company_id;
    MmapColumn<int32_t>  ci_movie_id_off, ci_person_id;
    MmapColumn<int32_t>  an_pid_off;

    {
        GENDB_PHASE("data_loading");
        kw_off.open(store + "/keyword/keyword.off");
        kw_dat.open(store + "/keyword/keyword.dat");

        cn_cc.open(store + "/company_name/country_code.bin");
        cn_cc_dict_off.open(store + "/company_name/country_code.dict.off");
        cn_cc_dict_dat.open(store + "/company_name/country_code.dict.dat");

        t_ep.open(store + "/title/episode_nr.bin");
        t_off.open(store + "/title/title.off");
        t_dat.open(store + "/title/title.dat");

        mk_k_csr_off.open(store + "/_idx/movie_keyword__keyword_id__offsets.bin");
        mk_k_csr_row.open(store + "/_idx/movie_keyword__keyword_id__rowids.bin");
        mk_movie_id.open(store + "/movie_keyword/movie_id.bin");

        mc_movie_id_off.open(store + "/_idx/movie_companies__movie_id__offsets.bin");
        mc_company_id.open(store + "/movie_companies/company_id.bin");

        ci_movie_id_off.open(store + "/_idx/cast_info__movie_id__offsets.bin");
        ci_person_id.open(store + "/cast_info/person_id.bin");

        an_pid_off.open(store + "/_idx/aka_name__person_id__offsets.bin");
        an_off.open(store + "/aka_name/name.off");
        an_dat.open(store + "/aka_name/name.dat");
    }

    // -------- Resolve constants --------
    int32_t k_id = -1;
    int16_t us_code = -1;

    {
        GENDB_PHASE("resolve_constants");
        // Resolve k_id: scan keyword varlen for "character-name-in-title"
        const char* target_kw = "character-name-in-title";
        size_t target_kw_len = std::strlen(target_kw);
        size_t n_kw = kw_off.count - 1;
        for (size_t i = 0; i < n_kw; ++i) {
            uint64_t s = kw_off[i], e = kw_off[i+1];
            if ((size_t)(e - s) == target_kw_len &&
                std::memcmp(kw_dat.data + s, target_kw, target_kw_len) == 0) {
                k_id = (int32_t)(i + 1); // 1-based id (dense PK)
                break;
            }
        }
        if (k_id < 0) {
            std::fprintf(stderr, "k_id not found\n");
            return 2;
        }

        // Resolve us_code: dictionary index of "[us]"
        const char* target_cc = "[us]";
        size_t target_cc_len = std::strlen(target_cc);
        size_t n_codes = cn_cc_dict_off.count - 1;
        for (size_t i = 0; i < n_codes; ++i) {
            uint64_t s = cn_cc_dict_off[i], e = cn_cc_dict_off[i+1];
            if ((size_t)(e - s) == target_cc_len &&
                std::memcmp(cn_cc_dict_dat.data + s, target_cc, target_cc_len) == 0) {
                us_code = (int16_t)i;
                break;
            }
        }
        if (us_code < 0) {
            std::fprintf(stderr, "us_code not found\n");
            return 2;
        }
    }

    // -------- Build cn_us_bitset over company_id (1-based) --------
    const size_t n_cn = cn_cc.count; // 234997
    std::vector<uint64_t> cn_us_bs((n_cn + 63) / 64, 0);
    {
        GENDB_PHASE("build_cn_us_bitset");
        for (size_t i = 0; i < n_cn; ++i) {
            if (cn_cc[i] == us_code) {
                cn_us_bs[i >> 6] |= (uint64_t)1 << (i & 63);
            }
        }
    }

    // -------- MIN registers (varlen via raw offsets) --------
    // We store the current best as (data_ptr, len).
    const char* min_an_ptr = nullptr; size_t min_an_len = 0; bool have_an = false;
    const char* min_t_ptr  = nullptr; size_t min_t_len  = 0; bool have_t  = false;

    auto lex_less = [](const char* a, size_t al, const char* b, size_t bl) {
        size_t m = al < bl ? al : bl;
        int c = std::memcmp(a, b, m);
        if (c != 0) return c < 0;
        return al < bl;
    };

    // -------- Main scan --------
    {
        GENDB_PHASE("main_scan");
        int32_t lo = mk_k_csr_off[k_id];
        int32_t hi = mk_k_csr_off[k_id + 1];

        for (int32_t k = lo; k < hi; ++k) {
            int32_t mk_row = mk_k_csr_row[k];
            int32_t mv = mk_movie_id[mk_row]; // 1-based movie/title id

            // Title episode filter (mv is 1-based)
            int32_t ep = t_ep[mv - 1];
            if (ep == INT32_MIN || ep >= 100) continue;

            // movie_companies probe: any mc row with company_id where cn_us_bs is set
            // Offsets-only index is 1-indexed: offsets[mv]=start, offsets[mv+1]=end.
            int32_t mc_lo = mc_movie_id_off[mv];
            int32_t mc_hi = mc_movie_id_off[mv + 1];
            bool us_match = false;
            for (int32_t j = mc_lo; j < mc_hi; ++j) {
                int32_t cid = mc_company_id[j]; // 1-based
                size_t idx = (size_t)(cid - 1);
                if (idx < n_cn && ((cn_us_bs[idx >> 6] >> (idx & 63)) & 1ULL)) {
                    us_match = true;
                    break;
                }
            }
            if (!us_match) continue;

            // mv survives — update MIN(t.title)
            uint64_t ts = t_off[mv - 1], te = t_off[mv];
            const char* tp = t_dat.data + ts;
            size_t tl = (size_t)(te - ts);
            if (!have_t || lex_less(tp, tl, min_t_ptr, min_t_len)) {
                min_t_ptr = tp; min_t_len = tl; have_t = true;
            }

            // cast_info probe: enumerate ci rows for mv -> get pids
            int32_t ci_lo = ci_movie_id_off[mv];
            int32_t ci_hi = ci_movie_id_off[mv + 1];
            for (int32_t c = ci_lo; c < ci_hi; ++c) {
                int32_t pid = ci_person_id[c]; // 1-based

                // aka_name probe: enumerate an rows for pid (offsets indexed by pid directly)
                int32_t an_lo = an_pid_off[pid];
                int32_t an_hi = an_pid_off[pid + 1];
                for (int32_t a = an_lo; a < an_hi; ++a) {
                    uint64_t as = an_off[a], ae = an_off[a + 1];
                    const char* ap = an_dat.data + as;
                    size_t al = (size_t)(ae - as);
                    if (!have_an || lex_less(ap, al, min_an_ptr, min_an_len)) {
                        min_an_ptr = ap; min_an_len = al; have_an = true;
                    }
                }
            }
        }
    }

    // -------- Output --------
    {
        GENDB_PHASE("output");
        std::string out_path = results_dir + "/Q16c.csv";
        FILE* fp = std::fopen(out_path.c_str(), "w");
        if (!fp) {
            std::fprintf(stderr, "Cannot open %s\n", out_path.c_str());
            return 3;
        }
        std::fprintf(fp, "cool_actor_pseudonym,series_named_after_char\n");

        auto write_csv_field = [&](const char* s, size_t n) {
            // CSV-escape: if contains , " \n \r or starts/ends with space, quote it
            bool need_quote = false;
            for (size_t i = 0; i < n; ++i) {
                char c = s[i];
                if (c == ',' || c == '"' || c == '\n' || c == '\r') { need_quote = true; break; }
            }
            if (!need_quote) {
                std::fwrite(s, 1, n, fp);
            } else {
                std::fputc('"', fp);
                for (size_t i = 0; i < n; ++i) {
                    char c = s[i];
                    if (c == '"') std::fputc('"', fp);
                    std::fputc(c, fp);
                }
                std::fputc('"', fp);
            }
        };

        if (have_an) write_csv_field(min_an_ptr, min_an_len);
        std::fputc(',', fp);
        if (have_t)  write_csv_field(min_t_ptr,  min_t_len);
        std::fputc('\n', fp);
        std::fclose(fp);
    }

    return 0;
}
