// Q9a — generated by GenDB Code Generator
// Person-driven star join with bitset semi-joins for movie filters.

#define _GNU_SOURCE
#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <climits>
#include <string>
#include <string_view>
#include <vector>
#include <algorithm>
#include <atomic>
#include <fstream>
#include <filesystem>
#include <fcntl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>
#include <omp.h>

#include "timing_utils.h"
#include "mmap_utils.h"
#include "cli_params.h"

using gendb::MmapColumn;

static std::string read_file_to_string(const std::string& path) {
    int fd = ::open(path.c_str(), O_RDONLY);
    if (fd < 0) { std::perror(path.c_str()); std::exit(1); }
    struct stat st;
    if (fstat(fd, &st) < 0) { std::perror("fstat"); std::exit(1); }
    std::string s;
    s.resize(st.st_size);
    ssize_t got = 0;
    while (got < st.st_size) {
        ssize_t r = ::read(fd, s.data() + got, st.st_size - got);
        if (r <= 0) break;
        got += r;
    }
    ::close(fd);
    return s;
}

static inline bool memmem_contains(const char* hay, size_t hl, const char* needle, size_t nl) {
    return memmem(hay, hl, needle, nl) != nullptr;
}

int main(int argc, char* argv[]) {
    GENDB_PHASE("total");
    if (argc < 3) {
        std::fprintf(stderr, "usage: q9a <gendb_dir> <results_dir>\n");
        return 1;
    }
    std::string store  = argv[1];
    std::string outdir = argv[2];
    std::filesystem::create_directories(outdir);

    // -------------------- mmap all columns --------------------
    MmapColumn<int8_t>  n_gender;
    MmapColumn<int64_t> n_name_off;
    MmapColumn<char>    n_name_dat;

    MmapColumn<int16_t> cn_cc;

    MmapColumn<int64_t> mc_note_off;
    MmapColumn<char>    mc_note_dat;
    MmapColumn<int32_t> mc_movie_id;
    MmapColumn<int32_t> mc_company_id;

    MmapColumn<int32_t> t_py;
    MmapColumn<int64_t> t_title_off;
    MmapColumn<char>    t_title_dat;

    MmapColumn<int64_t> ci_note_off;
    MmapColumn<char>    ci_note_dat;
    MmapColumn<int32_t> ci_role_id;
    MmapColumn<int32_t> ci_movie_id;
    MmapColumn<int32_t> ci_person_role_id;

    MmapColumn<int64_t> chn_name_off;
    MmapColumn<char>    chn_name_dat;

    MmapColumn<int32_t> an_pid;
    MmapColumn<int64_t> an_name_off;
    MmapColumn<char>    an_name_dat;

    MmapColumn<int32_t> cipid_off, cipid_row;
    MmapColumn<int32_t> akpid_off;

    {
        GENDB_PHASE("data_loading");
        n_gender.open(store + "/name/gender.bin");
        n_name_off.open(store + "/name/name.off");
        n_name_dat.open(store + "/name/name.dat");

        cn_cc.open(store + "/company_name/country_code.bin");

        mc_note_off.open(store + "/movie_companies/note.off");
        mc_note_dat.open(store + "/movie_companies/note.dat");
        mc_movie_id.open(store + "/movie_companies/movie_id.bin");
        mc_company_id.open(store + "/movie_companies/company_id.bin");

        t_py.open(store + "/title/production_year.bin");
        t_title_off.open(store + "/title/title.off");
        t_title_dat.open(store + "/title/title.dat");

        ci_note_off.open(store + "/cast_info/note.off");
        ci_note_dat.open(store + "/cast_info/note.dat");
        ci_role_id.open(store + "/cast_info/role_id.bin");
        ci_movie_id.open(store + "/cast_info/movie_id.bin");
        ci_person_role_id.open(store + "/cast_info/person_role_id.bin");

        chn_name_off.open(store + "/char_name/name.off");
        chn_name_dat.open(store + "/char_name/name.dat");

        an_pid.open(store + "/aka_name/person_id.bin");
        an_name_off.open(store + "/aka_name/name.off");
        an_name_dat.open(store + "/aka_name/name.dat");

        cipid_off.open(store + "/_idx/cast_info__person_id__offsets.bin");
        cipid_row.open(store + "/_idx/cast_info__person_id__rowids.bin");
        akpid_off.open(store + "/_idx/aka_name__person_id__offsets.bin");

        // Fire kernel readahead concurrently.
        gendb::mmap_prefetch_all(ci_role_id, ci_movie_id, ci_person_role_id);
        ci_note_off.prefetch();
        ci_note_dat.prefetch();
        cipid_off.prefetch();
        cipid_row.prefetch();
    }

    // -------------------- resolve dict codes --------------------
    int32_t rt_id_actress = 0;
    int16_t us_code = 0;
    int8_t  f_code  = 0;
    {
        GENDB_PHASE("resolve_dict_codes");

        {
            std::string rt_dat = read_file_to_string(store + "/role_type/role.dat");
            std::string offb   = read_file_to_string(store + "/role_type/role.off");
            const int64_t* rt_off = reinterpret_cast<const int64_t*>(offb.data());
            size_t n = offb.size() / sizeof(int64_t);
            for (size_t i = 0; i + 1 < n; ++i) {
                std::string_view s(rt_dat.data() + rt_off[i], rt_off[i+1] - rt_off[i]);
                if (s == "actress") { rt_id_actress = (int32_t)(i + 1); break; }
            }
        }
        {
            std::string cc_dat = read_file_to_string(store + "/company_name/country_code.dict.dat");
            std::string offb   = read_file_to_string(store + "/company_name/country_code.dict.off");
            const int64_t* cc_off = reinterpret_cast<const int64_t*>(offb.data());
            size_t n = offb.size() / sizeof(int64_t);
            for (size_t i = 0; i + 1 < n; ++i) {
                std::string_view s(cc_dat.data() + cc_off[i], cc_off[i+1] - cc_off[i]);
                if (s == "[us]") { us_code = (int16_t)(i + 1); break; }
            }
        }
        {
            std::string g_dat = read_file_to_string(store + "/name/gender.dict.dat");
            std::string offb  = read_file_to_string(store + "/name/gender.dict.off");
            const int64_t* g_off = reinterpret_cast<const int64_t*>(offb.data());
            size_t n = offb.size() / sizeof(int64_t);
            for (size_t i = 0; i + 1 < n; ++i) {
                std::string_view s(g_dat.data() + g_off[i], g_off[i+1] - g_off[i]);
                if (s == "f") { f_code = (int8_t)(i + 1); break; }
            }
        }
    }
    if (rt_id_actress == 0 || us_code == 0 || f_code == 0) {
        std::fprintf(stderr, "Failed to resolve dict codes (rt=%d us=%d f=%d)\n",
                     (int)rt_id_actress, (int)us_code, (int)f_code);
        return 1;
    }

    const size_t title_rows   = t_py.count;
    const size_t company_rows = cn_cc.count;
    const size_t name_rows    = n_gender.count;
    const size_t mc_rows      = mc_movie_id.count;

    // -------------------- cn_us bitset --------------------
    std::vector<uint8_t> cn_us(company_rows, 0);
    {
        GENDB_PHASE("build_cn_us");
        #pragma omp parallel for schedule(static)
        for (size_t i = 0; i < company_rows; ++i) {
            cn_us[i] = (cn_cc[i] == us_code) ? 1 : 0;
        }
    }

    // -------------------- year_ok bitset --------------------
    std::vector<uint8_t> year_ok(title_rows, 0);
    {
        GENDB_PHASE("build_year_ok");
        #pragma omp parallel for schedule(static)
        for (size_t i = 0; i < title_rows; ++i) {
            int32_t y = t_py[i];
            year_ok[i] = (y >= 2005 && y <= 2015) ? 1 : 0;
        }
    }

    // -------------------- movie_ok bitset --------------------
    // Scan movie_companies, AND with year_ok and cn_us, set bit per qualifying movie_id.
    std::vector<uint8_t> movie_ok(title_rows, 0);
    {
        GENDB_PHASE("build_movie_ok");
        #pragma omp parallel for schedule(static)
        for (size_t r = 0; r < mc_rows; ++r) {
            int64_t a = mc_note_off[r];
            int64_t b = mc_note_off[r + 1];
            if (b <= a) continue;  // note IS NULL → empty slice
            const char* nd = mc_note_dat.data + a;
            size_t nl = (size_t)(b - a);
            if (!(memmem_contains(nd, nl, "(USA)", 5) ||
                  memmem_contains(nd, nl, "(worldwide)", 11))) continue;
            int32_t cid = mc_company_id[r];
            if (cid <= 0 || (size_t)cid > company_rows) continue;
            if (!cn_us[cid - 1]) continue;
            int32_t mv = mc_movie_id[r];
            if (mv <= 0 || (size_t)mv > title_rows) continue;
            if (!year_ok[mv - 1]) continue;
            movie_ok[mv - 1] = 1;  // benign race (same value)
        }
    }

    // -------------------- candidate pids --------------------
    std::vector<int32_t> pids;
    {
        GENDB_PHASE("build_pids");
        int nthr = omp_get_max_threads();
        std::vector<std::vector<int32_t>> tlocal(nthr);

        #pragma omp parallel
        {
            int tid = omp_get_thread_num();
            auto& lv = tlocal[tid];
            #pragma omp for schedule(static)
            for (size_t i = 0; i < name_rows; ++i) {
                if (n_gender[i] != f_code) continue;
                int64_t a = n_name_off[i], b = n_name_off[i + 1];
                if (b - a < 3) continue;
                if (memmem(n_name_dat.data + a, (size_t)(b - a), "Ang", 3)) {
                    lv.push_back((int32_t)(i + 1));
                }
            }
        }
        size_t total = 0;
        for (auto& v : tlocal) total += v.size();
        pids.reserve(total);
        for (auto& v : tlocal) pids.insert(pids.end(), v.begin(), v.end());
        std::sort(pids.begin(), pids.end());
    }

    // -------------------- voice note IN check --------------------
    auto note_is_voice = [&](int32_t r) -> bool {
        int64_t a = ci_note_off[r], b = ci_note_off[r + 1];
        size_t l = (size_t)(b - a);
        const char* s = ci_note_dat.data + a;
        // "(voice)"=7, "(voice) (uncredited)"=20, "(voice: English version)"=24,
        // "(voice: Japanese version)"=25
        switch (l) {
            case 7:  return std::memcmp(s, "(voice)", 7) == 0;
            case 20: return std::memcmp(s, "(voice) (uncredited)", 20) == 0;
            case 24: return std::memcmp(s, "(voice: English version)", 24) == 0;
            case 25: return std::memcmp(s, "(voice: Japanese version)", 25) == 0;
            default: return false;
        }
    };

    // -------------------- main scan --------------------
    struct Local {
        std::string_view an, chn, t;
        bool have_an = false, have_chn = false, have_t = false;
    };
    int nthr = omp_get_max_threads();
    std::vector<Local> locals(nthr);

    const size_t chn_rows = chn_name_off.count > 0 ? chn_name_off.count - 1 : 0;
    const size_t an_rows  = an_name_off.count > 0 ? an_name_off.count - 1 : 0;
    (void)an_rows;

    {
        GENDB_PHASE("main_scan");
        #pragma omp parallel
        {
            int tid = omp_get_thread_num();
            Local& L = locals[tid];

            #pragma omp for schedule(dynamic, 64)
            for (size_t pi = 0; pi < pids.size(); ++pi) {
                int32_t pid = pids[pi];

                // aka_name must be non-empty (semi-join)
                int32_t aklo = akpid_off[pid];
                int32_t akhi = akpid_off[pid + 1];
                if (aklo >= akhi) continue;

                // Cast_info CSR probe
                int32_t cilo = cipid_off[pid];
                int32_t cihi = cipid_off[pid + 1];
                bool any_qualifying = false;
                for (int32_t k = cilo; k < cihi; ++k) {
                    int32_t r = cipid_row[k];
                    if (ci_role_id[r] != rt_id_actress) continue;
                    int32_t prid = ci_person_role_id[r];
                    if (prid == INT32_MIN) continue;
                    int32_t mv = ci_movie_id[r];
                    if (mv <= 0 || (size_t)mv > title_rows) continue;
                    if (!movie_ok[mv - 1]) continue;
                    if (!note_is_voice(r)) continue;

                    any_qualifying = true;

                    // title
                    int64_t ta = t_title_off[mv - 1], tb = t_title_off[mv];
                    std::string_view tv(t_title_dat.data + ta, (size_t)(tb - ta));
                    if (!L.have_t || tv < L.t) { L.t = tv; L.have_t = true; }

                    // char_name (dense PK)
                    if (prid >= 1 && (size_t)prid <= chn_rows) {
                        int64_t ca = chn_name_off[prid - 1], cb = chn_name_off[prid];
                        std::string_view cv(chn_name_dat.data + ca, (size_t)(cb - ca));
                        if (!L.have_chn || cv < L.chn) { L.chn = cv; L.have_chn = true; }
                    }
                }

                if (any_qualifying) {
                    // aka_name rows for this pid (data sorted by person_id)
                    for (int32_t k = aklo; k < akhi; ++k) {
                        int64_t aa = an_name_off[k], ab = an_name_off[k + 1];
                        std::string_view av(an_name_dat.data + aa, (size_t)(ab - aa));
                        if (!L.have_an || av < L.an) { L.an = av; L.have_an = true; }
                    }
                }
            }
        }
    }

    // -------------------- reduce --------------------
    std::string min_an, min_chn, min_t;
    bool have_an = false, have_chn = false, have_t = false;
    for (auto& L : locals) {
        if (L.have_an  && (!have_an  || L.an  < std::string_view(min_an)))  { min_an  = std::string(L.an);  have_an  = true; }
        if (L.have_chn && (!have_chn || L.chn < std::string_view(min_chn))) { min_chn = std::string(L.chn); have_chn = true; }
        if (L.have_t   && (!have_t   || L.t   < std::string_view(min_t)))   { min_t   = std::string(L.t);   have_t   = true; }
    }

    // -------------------- output --------------------
    {
        GENDB_PHASE("output");
        std::string out_path = outdir + "/Q9a.csv";
        std::ofstream f(out_path);
        f << "alternative_name,character_name,movie\n";
        f << min_an << "," << min_chn << "," << min_t << "\n";
    }

    return 0;
}
