// Q14a — Generated by GenDB
// MIN(mi_idx.info), MIN(t.title) over star join filtered by:
//   info_type.info='countries' (it1), info_type.info='rating' (it2),
//   keyword IN (...), kind_type='movie', mi.info IN (10 countries),
//   mi_idx.info < '8.5' (lex), t.production_year > 2010.
//
// Title-driven scan with offsets_only join lookups into mk, mi, mi_idx.
// Parallelized with OpenMP (morsel-driven).

#include <cstdio>
#include <cstdint>
#include <cstring>
#include <climits>
#include <string>
#include <string_view>
#include <vector>
#include <algorithm>
#include <stdexcept>
#include <filesystem>
#include <omp.h>

#include "timing_utils.h"
#include "mmap_utils.h"

using gendb::MmapColumn;

static std::string read_file(const std::string& path) {
    FILE* f = std::fopen(path.c_str(), "rb");
    if (!f) throw std::runtime_error("cannot open " + path);
    std::fseek(f, 0, SEEK_END);
    long sz = std::ftell(f);
    std::fseek(f, 0, SEEK_SET);
    std::string s;
    s.resize((size_t)sz);
    if (sz > 0 && std::fread(s.data(), 1, (size_t)sz, f) != (size_t)sz) {
        std::fclose(f);
        throw std::runtime_error("short read " + path);
    }
    std::fclose(f);
    return s;
}

static inline bool lex_lt(std::string_view a, std::string_view b) {
    size_t n = std::min(a.size(), b.size());
    int c = std::memcmp(a.data(), b.data(), n);
    return c < 0 || (c == 0 && a.size() < b.size());
}

int main(int argc, char** argv) {
    if (argc < 3) {
        std::fprintf(stderr, "usage: %s <gendb_dir> <results_dir>\n", argv[0]);
        return 2;
    }
    GENDB_PHASE("total");

    std::string store = argv[1];
    std::string results_dir = argv[2];
    std::filesystem::create_directories(results_dir);

    int32_t it1_id = 0, it2_id = 0, kt_id = 0;
    std::vector<int32_t> k_ids;  // ~4 entries, linear scan

    // ---- dim resolution + mmap setup ----
    MmapColumn<int32_t> t_kind_id;
    MmapColumn<int32_t> t_year;
    MmapColumn<int64_t> t_title_off;
    std::string t_title_dat;

    MmapColumn<int32_t> mk_keyword_id;
    MmapColumn<int32_t> mkmid;  // offsets for movie_keyword.movie_id

    MmapColumn<int32_t> mi_info_type_id;
    MmapColumn<int64_t> mi_info_off;
    std::string mi_info_dat;
    MmapColumn<int32_t> mimid;

    MmapColumn<int32_t> mix_info_type_id;
    MmapColumn<int64_t> mix_info_off;
    std::string mix_info_dat;
    MmapColumn<int32_t> mixmid;

    {
        GENDB_PHASE("data_loading");

        // info_type
        {
            std::string off_path = store + "/info_type/info.off";
            std::string dat_path = store + "/info_type/info.dat";
            MmapColumn<int64_t> off(off_path);
            std::string dat = read_file(dat_path);
            for (size_t i = 0; i + 1 < off.size(); ++i) {
                std::string_view s(dat.data() + off[i], (size_t)(off[i+1] - off[i]));
                if (s == "countries") it1_id = (int32_t)(i + 1);
                else if (s == "rating") it2_id = (int32_t)(i + 1);
            }
        }

        // kind_type
        {
            MmapColumn<int64_t> off(store + "/kind_type/kind.off");
            std::string dat = read_file(store + "/kind_type/kind.dat");
            for (size_t i = 0; i + 1 < off.size(); ++i) {
                std::string_view s(dat.data() + off[i], (size_t)(off[i+1] - off[i]));
                if (s == "movie") { kt_id = (int32_t)(i + 1); break; }
            }
        }

        // keyword set (4 ids expected)
        {
            MmapColumn<int64_t> off(store + "/keyword/keyword.off");
            std::string dat = read_file(store + "/keyword/keyword.dat");
            static const std::string_view wanted[] = {
                std::string_view("murder"),
                std::string_view("murder-in-title"),
                std::string_view("blood"),
                std::string_view("violence"),
            };
            for (size_t i = 0; i + 1 < off.size(); ++i) {
                std::string_view s(dat.data() + off[i], (size_t)(off[i+1] - off[i]));
                for (auto w : wanted) {
                    if (s == w) { k_ids.push_back((int32_t)(i + 1)); break; }
                }
            }
        }

        // title columns
        t_kind_id.open(store + "/title/kind_id.bin");
        t_year.open(store + "/title/production_year.bin");
        t_title_off.open(store + "/title/title.off");
        t_title_dat = read_file(store + "/title/title.dat");

        // movie_keyword + offsets
        mk_keyword_id.open(store + "/movie_keyword/keyword_id.bin");
        mkmid.open(store + "/_idx/movie_keyword__movie_id__offsets.bin");
        mk_keyword_id.advise_random();

        // movie_info + offsets
        mi_info_type_id.open(store + "/movie_info/info_type_id.bin");
        mi_info_off.open(store + "/movie_info/info.off");
        mi_info_dat = read_file(store + "/movie_info/info.dat");
        mimid.open(store + "/_idx/movie_info__movie_id__offsets.bin");
        mi_info_type_id.advise_random();
        mi_info_off.advise_random();

        // movie_info_idx + offsets
        mix_info_type_id.open(store + "/movie_info_idx/info_type_id.bin");
        mix_info_off.open(store + "/movie_info_idx/info.off");
        mix_info_dat = read_file(store + "/movie_info_idx/info.dat");
        mixmid.open(store + "/_idx/movie_info_idx__movie_id__offsets.bin");
    }

    if (it1_id == 0 || it2_id == 0 || kt_id == 0 || k_ids.empty()) {
        std::fprintf(stderr, "dim resolution failed: it1=%d it2=%d kt=%d kids=%zu\n",
                     it1_id, it2_id, kt_id, k_ids.size());
        // emit empty result
        std::string out_path = results_dir + "/Q14a.csv";
        FILE* f = std::fopen(out_path.c_str(), "w");
        std::fprintf(f, "rating,northern_dark_movie\n");
        std::fclose(f);
        return 0;
    }

    // Compact k_ids (typically 4) into small array for fast linear search.
    int32_t k_arr[16] = {0};
    int32_t k_n = (int32_t)std::min(k_ids.size(), (size_t)16);
    for (int32_t i = 0; i < k_n; ++i) k_arr[i] = k_ids[i];

    // Precompute country lengths and pointers for length-prefix dispatch.
    static const std::string_view countries[] = {
        std::string_view("Sweden"),
        std::string_view("Norway"),
        std::string_view("Germany"),
        std::string_view("Denmark"),
        std::string_view("Swedish"),
        std::string_view("Denish"),
        std::string_view("Norwegian"),
        std::string_view("German"),
        std::string_view("USA"),
        std::string_view("American"),
    };
    constexpr int N_CTR = 10;
    int c_len[N_CTR];
    const char* c_ptr[N_CTR];
    for (int i = 0; i < N_CTR; ++i) { c_len[i] = (int)countries[i].size(); c_ptr[i] = countries[i].data(); }

    const std::string_view RATING_LIMIT("8.5");

    // ---- main scan: title-driven, parallel ----
    size_t n_titles = t_kind_id.size();
    int num_threads = std::max(1, omp_get_max_threads());

    std::vector<std::string> per_thread_min_rating(num_threads);
    std::vector<std::string> per_thread_min_title(num_threads);

    {
        GENDB_PHASE("main_scan");

        const int32_t* tkind = t_kind_id.data;
        const int32_t* tyear = t_year.data;
        const int64_t* toff  = t_title_off.data;
        const char*    tdat  = t_title_dat.data();

        const int32_t* mk_kw = mk_keyword_id.data;
        const int32_t* mk_off = mkmid.data;

        const int32_t* mi_it = mi_info_type_id.data;
        const int64_t* mi_off = mi_info_off.data;
        const char*    mi_dat = mi_info_dat.data();
        const int32_t* mi_movoff = mimid.data;

        const int32_t* mix_it = mix_info_type_id.data;
        const int64_t* mix_off = mix_info_off.data;
        const char*    mix_dat = mix_info_dat.data();
        const int32_t* mix_movoff = mixmid.data;

        #pragma omp parallel
        {
            int tid = omp_get_thread_num();
            std::string local_rating;
            std::string local_title;
            bool has_rating = false, has_title = false;

            #pragma omp for schedule(dynamic, 32768) nowait
            for (size_t r = 0; r < n_titles; ++r) {
                int32_t y = tyear[r];
                if (y == INT32_MIN || y <= 2010) continue;
                if (tkind[r] != kt_id) continue;

                int32_t mv = (int32_t)(r + 1);

                // --- semi-join movie_keyword ---
                int32_t klo = mk_off[mv];
                int32_t khi = mk_off[mv + 1];
                bool kw_ok = false;
                for (int32_t i = klo; i < khi; ++i) {
                    int32_t kid = mk_kw[i];
                    for (int32_t j = 0; j < k_n; ++j) {
                        if (kid == k_arr[j]) { kw_ok = true; break; }
                    }
                    if (kw_ok) break;
                }
                if (!kw_ok) continue;

                // --- semi-join movie_info (country) ---
                int32_t milo = mi_movoff[mv];
                int32_t mihi = mi_movoff[mv + 1];
                bool mi_ok = false;
                for (int32_t i = milo; i < mihi; ++i) {
                    if (mi_it[i] != it1_id) continue;
                    int64_t s0 = mi_off[i];
                    int64_t s1 = mi_off[i + 1];
                    int slen = (int)(s1 - s0);
                    const char* sptr = mi_dat + s0;
                    for (int c = 0; c < N_CTR; ++c) {
                        if (c_len[c] == slen && std::memcmp(sptr, c_ptr[c], (size_t)slen) == 0) {
                            mi_ok = true;
                            break;
                        }
                    }
                    if (mi_ok) break;
                }
                if (!mi_ok) continue;

                // --- inner-aggregate movie_info_idx (rating < '8.5') ---
                int32_t xlo = mix_movoff[mv];
                int32_t xhi = mix_movoff[mv + 1];
                bool produced = false;
                for (int32_t i = xlo; i < xhi; ++i) {
                    if (mix_it[i] != it2_id) continue;
                    int64_t s0 = mix_off[i];
                    int64_t s1 = mix_off[i + 1];
                    std::string_view info(mix_dat + s0, (size_t)(s1 - s0));
                    if (!lex_lt(info, RATING_LIMIT)) continue;
                    produced = true;
                    if (!has_rating || lex_lt(info, std::string_view(local_rating))) {
                        local_rating.assign(info.data(), info.size());
                        has_rating = true;
                    }
                }
                if (!produced) continue;

                // Title participates in at least one output tuple; update MIN(title).
                int64_t t0 = toff[r];
                int64_t t1 = toff[r + 1];
                std::string_view title(tdat + t0, (size_t)(t1 - t0));
                if (!has_title || lex_lt(title, std::string_view(local_title))) {
                    local_title.assign(title.data(), title.size());
                    has_title = true;
                }
            }

            if (has_rating) per_thread_min_rating[tid] = std::move(local_rating);
            if (has_title)  per_thread_min_title[tid]  = std::move(local_title);
        }
    }

    // ---- reduction ----
    std::string min_rating, min_title;
    bool has_r = false, has_t = false;
    for (int i = 0; i < num_threads; ++i) {
        if (!per_thread_min_rating[i].empty() || (i < (int)per_thread_min_rating.size() && per_thread_min_rating[i].size() == 0 && false)) {}
        // Note: an empty info string is theoretically possible but extremely unlikely here.
        // Track non-empty as "present"; for full correctness check size>0 OR a parallel flag.
    }
    // Use a more careful reduction: any thread that wrote something has it.
    // (We never assigned an empty string above.)
    for (int i = 0; i < num_threads; ++i) {
        const std::string& r = per_thread_min_rating[i];
        if (!r.empty()) {
            if (!has_r || lex_lt(std::string_view(r), std::string_view(min_rating))) {
                min_rating = r; has_r = true;
            }
        }
        const std::string& t = per_thread_min_title[i];
        if (!t.empty()) {
            if (!has_t || lex_lt(std::string_view(t), std::string_view(min_title))) {
                min_title = t; has_t = true;
            }
        }
    }

    // ---- output ----
    {
        GENDB_PHASE("output");
        std::string out_path = results_dir + "/Q14a.csv";
        FILE* f = std::fopen(out_path.c_str(), "w");
        if (!f) throw std::runtime_error("cannot write " + out_path);
        std::fprintf(f, "rating,northern_dark_movie\n");
        if (has_r && has_t) {
            std::fprintf(f, "%.*s,%.*s\n",
                         (int)min_rating.size(), min_rating.data(),
                         (int)min_title.size(), min_title.data());
        }
        std::fclose(f);
    }

    return 0;
}
