// Q30a — generated by GenDB Code Generator
//
// SELECT MIN(mi.info) AS movie_budget, MIN(mi_idx.info) AS movie_votes,
//        MIN(n.name) AS writer, MIN(t.title) AS complete_violent_movie
//   FROM ... (see plan)
//
// Plan: drive on complete_cast (135K rows), filter on cct1/cct2, dedup mv set,
//       filter production_year > 2000, then per-mv probe mk/mi/mi_idx/ci.

#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <climits>
#include <string>
#include <string_view>
#include <vector>
#include <unordered_set>
#include <unordered_map>
#include <algorithm>
#include <fstream>
#include <sys/stat.h>
#include <sys/types.h>

#include "timing_utils.h"
#include "mmap_utils.h"

using gendb::MmapColumn;

// -----------------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------------
static inline std::string_view sv_from(const char* data, int64_t lo, int64_t hi) {
    return std::string_view(data + lo, static_cast<size_t>(hi - lo));
}

static void mkdir_p(const std::string& path) {
    std::string cur;
    for (size_t i = 0; i <= path.size(); ++i) {
        if (i == path.size() || path[i] == '/') {
            if (!cur.empty()) ::mkdir(cur.c_str(), 0755);
        }
        if (i < path.size()) cur.push_back(path[i]);
    }
}

// CSV-escape: wrap in quotes if contains comma, quote, or newline; escape quotes.
static std::string csv_escape(std::string_view s) {
    bool need_quote = false;
    for (char c : s) {
        if (c == ',' || c == '"' || c == '\n' || c == '\r') { need_quote = true; break; }
    }
    if (!need_quote) return std::string(s);
    std::string out;
    out.reserve(s.size() + 2);
    out.push_back('"');
    for (char c : s) {
        if (c == '"') out.push_back('"');
        out.push_back(c);
    }
    out.push_back('"');
    return out;
}

int main(int argc, char** argv) {
    if (argc < 3) {
        std::fprintf(stderr, "Usage: %s <gendb_dir> <results_dir>\n", argv[0]);
        return 1;
    }
    std::string gendb_dir = argv[1];
    std::string results_dir = argv[2];
    mkdir_p(results_dir);

    GENDB_PHASE("total");

    // ------------------------------------------------------------------
    // Open all column files (mmap is cheap, OS will page in on access)
    // ------------------------------------------------------------------
    MmapColumn<int32_t> cct_id;
    MmapColumn<char>    cct_kind_dat;
    MmapColumn<int64_t> cct_kind_off;

    MmapColumn<int32_t> it_id;
    MmapColumn<char>    it_info_dat;
    MmapColumn<int64_t> it_info_off;

    MmapColumn<int32_t> k_id;
    MmapColumn<char>    k_kw_dat;
    MmapColumn<int64_t> k_kw_off;

    // complete_cast
    MmapColumn<int32_t> cc_movie_id;
    MmapColumn<int32_t> cc_subject_id;
    MmapColumn<int32_t> cc_status_id;

    // title
    MmapColumn<int32_t> t_prod_year;
    MmapColumn<char>    t_title_dat;
    MmapColumn<int64_t> t_title_off;

    // movie_keyword
    MmapColumn<int32_t> mk_off;
    MmapColumn<int32_t> mk_keyword_id;

    // movie_info
    MmapColumn<int32_t> mi_off;
    MmapColumn<int32_t> mi_info_type_id;
    MmapColumn<char>    mi_info_dat;
    MmapColumn<int64_t> mi_info_off;

    // movie_info_idx
    MmapColumn<int32_t> mii_off;
    MmapColumn<int32_t> mii_info_type_id;
    MmapColumn<char>    mii_info_dat;
    MmapColumn<int64_t> mii_info_off;

    // cast_info
    MmapColumn<int32_t> ci_off;
    MmapColumn<int32_t> ci_person_id;
    MmapColumn<char>    ci_note_dat;
    MmapColumn<int64_t> ci_note_off;

    // name
    MmapColumn<int8_t>  n_gender;
    MmapColumn<char>    n_gender_dict_dat;
    MmapColumn<int64_t> n_gender_dict_off;
    MmapColumn<char>    n_name_dat;
    MmapColumn<int64_t> n_name_off;

    {
        GENDB_PHASE("data_loading");
        cct_id.open(gendb_dir + "/comp_cast_type/id.bin");
        cct_kind_dat.open(gendb_dir + "/comp_cast_type/kind.dat");
        cct_kind_off.open(gendb_dir + "/comp_cast_type/kind.off");

        it_id.open(gendb_dir + "/info_type/id.bin");
        it_info_dat.open(gendb_dir + "/info_type/info.dat");
        it_info_off.open(gendb_dir + "/info_type/info.off");

        k_id.open(gendb_dir + "/keyword/id.bin");
        k_kw_dat.open(gendb_dir + "/keyword/keyword.dat");
        k_kw_off.open(gendb_dir + "/keyword/keyword.off");

        cc_movie_id.open(gendb_dir + "/complete_cast/movie_id.bin");
        cc_subject_id.open(gendb_dir + "/complete_cast/subject_id.bin");
        cc_status_id.open(gendb_dir + "/complete_cast/status_id.bin");

        t_prod_year.open(gendb_dir + "/title/production_year.bin");
        t_title_dat.open(gendb_dir + "/title/title.dat");
        t_title_off.open(gendb_dir + "/title/title.off");

        mk_off.open(gendb_dir + "/_idx/movie_keyword__movie_id__offsets.bin");
        mk_keyword_id.open(gendb_dir + "/movie_keyword/keyword_id.bin");

        mi_off.open(gendb_dir + "/_idx/movie_info__movie_id__offsets.bin");
        mi_info_type_id.open(gendb_dir + "/movie_info/info_type_id.bin");
        mi_info_dat.open(gendb_dir + "/movie_info/info.dat");
        mi_info_off.open(gendb_dir + "/movie_info/info.off");

        mii_off.open(gendb_dir + "/_idx/movie_info_idx__movie_id__offsets.bin");
        mii_info_type_id.open(gendb_dir + "/movie_info_idx/info_type_id.bin");
        mii_info_dat.open(gendb_dir + "/movie_info_idx/info.dat");
        mii_info_off.open(gendb_dir + "/movie_info_idx/info.off");

        ci_off.open(gendb_dir + "/_idx/cast_info__movie_id__offsets.bin");
        ci_person_id.open(gendb_dir + "/cast_info/person_id.bin");
        ci_note_dat.open(gendb_dir + "/cast_info/note.dat");
        ci_note_off.open(gendb_dir + "/cast_info/note.off");

        n_gender.open(gendb_dir + "/name/gender.bin");
        n_gender_dict_dat.open(gendb_dir + "/name/gender.dict.dat");
        n_gender_dict_off.open(gendb_dir + "/name/gender.dict.off");
        n_name_dat.open(gendb_dir + "/name/name.dat");
        n_name_off.open(gendb_dir + "/name/name.off");
    }

    // ------------------------------------------------------------------
    // Resolve dimensions
    // ------------------------------------------------------------------
    std::unordered_set<int32_t> cct1_ids;
    int32_t cct2_id = INT32_MIN;
    int32_t it1_id  = INT32_MIN;
    int32_t it2_id  = INT32_MIN;
    std::unordered_set<int32_t> k_ids;
    int8_t  m_code  = -1;

    {
        GENDB_PHASE("dim_resolve");

        // comp_cast_type: kind IN ('cast','crew'), kind='complete+verified'
        for (size_t r = 0; r < cct_id.count; ++r) {
            int64_t lo = cct_kind_off[r], hi = cct_kind_off[r + 1];
            std::string_view kind = sv_from(cct_kind_dat.data, lo, hi);
            if (kind == "cast" || kind == "crew") cct1_ids.insert(cct_id[r]);
            else if (kind == "complete+verified") cct2_id = cct_id[r];
        }

        // info_type: info='genres', info='votes'
        for (size_t r = 0; r < it_id.count; ++r) {
            int64_t lo = it_info_off[r], hi = it_info_off[r + 1];
            std::string_view s = sv_from(it_info_dat.data, lo, hi);
            if (s == "genres") it1_id = it_id[r];
            else if (s == "votes") it2_id = it_id[r];
        }

        // keyword: 7 literals
        static const char* kKeywords[7] = {
            "murder", "violence", "blood", "gore",
            "death", "female-nudity", "hospital"
        };
        for (size_t r = 0; r < k_id.count; ++r) {
            int64_t lo = k_kw_off[r], hi = k_kw_off[r + 1];
            size_t len = static_cast<size_t>(hi - lo);
            // length prefilter (4..13)
            if (len < 4 || len > 13) continue;
            std::string_view s = sv_from(k_kw_dat.data, lo, hi);
            for (int i = 0; i < 7; ++i) {
                if (s == kKeywords[i]) { k_ids.insert(k_id[r]); break; }
            }
            if (k_ids.size() == 7) break;
        }

        // name.gender 'm' code — dict codes are 1-based (0 reserved for NULL)
        size_t nd = n_gender_dict_off.count > 0 ? n_gender_dict_off.count - 1 : 0;
        for (size_t r = 0; r < nd; ++r) {
            int64_t lo = n_gender_dict_off[r], hi = n_gender_dict_off[r + 1];
            if ((hi - lo) == 1 && n_gender_dict_dat.data[lo] == 'm') {
                m_code = static_cast<int8_t>(r + 1);
                break;
            }
        }
    }

    if (cct1_ids.empty() || cct2_id == INT32_MIN || it1_id == INT32_MIN ||
        it2_id == INT32_MIN || k_ids.empty() || m_code < 0) {
        std::fprintf(stderr, "Dim resolution failed\n");
        return 2;
    }

    // writer_note_set (string_view equality)
    static const char* kNotes[5] = {
        "(writer)", "(head writer)", "(written by)", "(story)", "(story editor)"
    };
    static const size_t kNoteLens[5] = { 8, 13, 12, 7, 15 };

    auto is_writer_note = [&](std::string_view s) -> bool {
        size_t len = s.size();
        for (int i = 0; i < 5; ++i) {
            if (len == kNoteLens[i] && std::memcmp(s.data(), kNotes[i], len) == 0)
                return true;
        }
        return false;
    };

    auto is_horror_or_thriller = [&](std::string_view s) -> bool {
        size_t len = s.size();
        if (len == 6) return std::memcmp(s.data(), "Horror", 6) == 0;
        if (len == 8) return std::memcmp(s.data(), "Thriller", 8) == 0;
        return false;
    };

    // ------------------------------------------------------------------
    // Driver: scan complete_cast, filter, dedup mv ids
    // ------------------------------------------------------------------
    std::vector<int32_t> mv_candidates;
    {
        GENDB_PHASE("driver_scan_cc");
        // Use unordered_set for dedup (cc has ~135K rows, candidates ~30K).
        std::unordered_set<int32_t> mv_set;
        mv_set.reserve(40000);
        const size_t N = cc_movie_id.count;
        // cct1_ids has at most 2 ids — branchless quick compare.
        std::vector<int32_t> cct1_vec(cct1_ids.begin(), cct1_ids.end());
        for (size_t r = 0; r < N; ++r) {
            int32_t mv = cc_movie_id[r];
            if (mv == INT32_MIN) continue;
            int32_t subj = cc_subject_id[r];
            int32_t stat = cc_status_id[r];
            if (stat != cct2_id) continue;
            bool ok = false;
            for (int32_t s : cct1_vec) {
                if (subj == s) { ok = true; break; }
            }
            if (!ok) continue;
            mv_set.insert(mv);
        }
        mv_candidates.assign(mv_set.begin(), mv_set.end());
        std::sort(mv_candidates.begin(), mv_candidates.end()); // sequential probe locality
    }

    // ------------------------------------------------------------------
    // Per-mv probing: title.production_year, mk semi, mi semi+capture,
    // mi_idx semi+capture, ci semi+capture(name).
    // Aggregate global mins (string_view minima).
    // ------------------------------------------------------------------
    std::string min_mi_info;       bool have_mi      = false;
    std::string min_mi_idx_info;   bool have_mi_idx  = false;
    std::string min_name;          bool have_name    = false;
    std::string min_title;         bool have_title   = false;

    {
        GENDB_PHASE("main_scan");

        // Local string holders for ranges within mv loop
        // (we copy because string_view aliases mmap; copying only on improvement is fine
        //  but we hold final values for output anyway).

        const int32_t* prod = t_prod_year.data;
        const int64_t prod_count = static_cast<int64_t>(t_prod_year.count);

        std::vector<int32_t> k_ids_vec(k_ids.begin(), k_ids.end());

        for (int32_t mv : mv_candidates) {
            if (mv <= 0 || static_cast<int64_t>(mv) > prod_count) continue;

            int32_t py = prod[mv - 1];
            if (py == INT32_MIN || py <= 2000) continue;

            // --- movie_keyword semi-join ---
            int32_t mk_lo = mk_off[mv];
            int32_t mk_hi = mk_off[mv + 1];
            bool mk_match = false;
            for (int32_t r = mk_lo; r < mk_hi; ++r) {
                int32_t kid = mk_keyword_id[r];
                for (int32_t k : k_ids_vec) {
                    if (kid == k) { mk_match = true; break; }
                }
                if (mk_match) break;
            }
            if (!mk_match) continue;

            // --- movie_info semi+capture (Horror/Thriller, it1) ---
            int32_t mi_lo = mi_off[mv];
            int32_t mi_hi = mi_off[mv + 1];
            std::string_view mv_mi_best;
            bool mv_mi_have = false;
            for (int32_t r = mi_lo; r < mi_hi; ++r) {
                if (mi_info_type_id[r] != it1_id) continue;
                int64_t lo = mi_info_off[r], hi = mi_info_off[r + 1];
                size_t len = static_cast<size_t>(hi - lo);
                if (len < 5 || len > 8) continue;
                std::string_view s = sv_from(mi_info_dat.data, lo, hi);
                if (!is_horror_or_thriller(s)) continue;
                if (!mv_mi_have || s < mv_mi_best) { mv_mi_best = s; mv_mi_have = true; }
            }
            if (!mv_mi_have) continue;

            // --- movie_info_idx semi+capture (it2) ---
            int32_t mii_lo = mii_off[mv];
            int32_t mii_hi = mii_off[mv + 1];
            std::string_view mv_mii_best;
            bool mv_mii_have = false;
            for (int32_t r = mii_lo; r < mii_hi; ++r) {
                if (mii_info_type_id[r] != it2_id) continue;
                int64_t lo = mii_info_off[r], hi = mii_info_off[r + 1];
                std::string_view s = sv_from(mii_info_dat.data, lo, hi);
                if (!mv_mii_have || s < mv_mii_best) { mv_mii_best = s; mv_mii_have = true; }
            }
            if (!mv_mii_have) continue;

            // --- cast_info semi+capture (writer notes, male) ---
            int32_t ci_lo = ci_off[mv];
            int32_t ci_hi = ci_off[mv + 1];
            std::string_view mv_name_best;
            bool mv_name_have = false;
            for (int32_t r = ci_lo; r < ci_hi; ++r) {
                int64_t no_lo = ci_note_off[r], no_hi = ci_note_off[r + 1];
                if (no_hi == no_lo) continue; // empty note
                std::string_view note = sv_from(ci_note_dat.data, no_lo, no_hi);
                if (!is_writer_note(note)) continue;
                int32_t pid = ci_person_id[r];
                if (pid <= 0 || static_cast<size_t>(pid) > n_gender.count) continue;
                if (n_gender[pid - 1] != m_code) continue;
                int64_t nm_lo = n_name_off[pid - 1], nm_hi = n_name_off[pid];
                std::string_view nm = sv_from(n_name_dat.data, nm_lo, nm_hi);
                if (!mv_name_have || nm < mv_name_best) { mv_name_best = nm; mv_name_have = true; }
            }
            if (!mv_name_have) continue;

            // --- title ---
            int64_t tt_lo = t_title_off[mv - 1], tt_hi = t_title_off[mv];
            std::string_view title = sv_from(t_title_dat.data, tt_lo, tt_hi);

            // Update global mins
            if (!have_mi      || mv_mi_best   < min_mi_info)     { min_mi_info     = std::string(mv_mi_best);   have_mi = true; }
            if (!have_mi_idx  || mv_mii_best  < min_mi_idx_info) { min_mi_idx_info = std::string(mv_mii_best);  have_mi_idx = true; }
            if (!have_name    || mv_name_best < min_name)        { min_name        = std::string(mv_name_best); have_name = true; }
            if (!have_title   || title        < min_title)       { min_title       = std::string(title);        have_title = true; }
        }
    }

    // ------------------------------------------------------------------
    // Output CSV
    // ------------------------------------------------------------------
    {
        GENDB_PHASE("output");
        std::string out_path = results_dir + "/Q30a.csv";
        std::ofstream out(out_path);
        out << "movie_budget,movie_votes,writer,complete_violent_movie\n";
        if (have_mi || have_mi_idx || have_name || have_title) {
            out << csv_escape(min_mi_info) << ","
                << csv_escape(min_mi_idx_info) << ","
                << csv_escape(min_name) << ","
                << csv_escape(min_title) << "\n";
        } else {
            out << ",,,\n";
        }
        out.close();
    }

    return 0;
}
