// Q33a — auto-generated by GenDB Code Generator
// Implements:
//   SELECT MIN(cn1.name), MIN(cn2.name), MIN(mi_idx1.info), MIN(mi_idx2.info),
//          MIN(t1.title), MIN(t2.title)
//   FROM ... WHERE cn1.country_code='[us]' AND it.info='rating'
//                 AND kt.kind='tv series' AND lt.link IN (sequel,follows,followed by)
//                 AND mi_idx2.info < '3.0' AND t2.production_year BETWEEN 2005 AND 2008
//                 AND ... joins ...
//
// Storage notes for this iteration's actual layout:
//   - varlen columns: <col>.off (int64 N+1) + <col>.dat
//   - dict-encoded country_code: int16 codes in country_code.bin; dict in
//     country_code.dict.off / .dict.dat (code 0 = NULL, code i -> dict entry i-1)
//   - index offsets in _idx/<child>__<fk>__offsets.bin are int32[(max_parent_id+2)]
//   - title, company_name, info_type, kind_type, link_type have id_is_dense_1_to_N
//     so PK pos lookup = id - 1.

#include <cstdio>
#include <cstdint>
#include <cstring>
#include <cstdlib>
#include <string>
#include <string_view>
#include <vector>
#include <algorithm>
#include <sys/mman.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <omp.h>
#include <stdexcept>
#include <filesystem>

#include "timing_utils.h"
#include "cli_params.h"

using namespace gendb;
namespace fs = std::filesystem;

// -----------------------------------------------------------------------------
// Minimal mmap helper (typed)
// -----------------------------------------------------------------------------
struct MM {
    const void* ptr = nullptr;
    size_t bytes = 0;
    int fd = -1;
    MM() = default;
    explicit MM(const std::string& p) { open(p); }
    void open(const std::string& path) {
        fd = ::open(path.c_str(), O_RDONLY);
        if (fd < 0) { fprintf(stderr, "cannot open %s\n", path.c_str()); std::exit(1); }
        struct stat st;
        fstat(fd, &st);
        bytes = (size_t)st.st_size;
        if (bytes == 0) { ptr = nullptr; return; }
        void* p = mmap(nullptr, bytes, PROT_READ, MAP_PRIVATE, fd, 0);
        if (p == MAP_FAILED) { fprintf(stderr, "mmap failed %s\n", path.c_str()); std::exit(1); }
        ptr = p;
        if (bytes > (1u<<20)) madvise(p, bytes, MADV_WILLNEED);
    }
    ~MM() {
        if (ptr && bytes) munmap(const_cast<void*>(ptr), bytes);
        if (fd >= 0) ::close(fd);
    }
    MM(MM&&) = delete;
    MM& operator=(MM&&) = delete;
    template<typename T> const T* as() const { return static_cast<const T*>(ptr); }
    template<typename T> size_t count() const { return bytes / sizeof(T); }
};

// -----------------------------------------------------------------------------
// Varlen helpers — .off is int64[N+1], .dat is raw bytes.
// -----------------------------------------------------------------------------
static inline std::string_view varlen_get(const int64_t* off, const char* dat, int64_t row) {
    int64_t a = off[row], b = off[row+1];
    return std::string_view(dat + a, (size_t)(b - a));
}

// -----------------------------------------------------------------------------
// CSV helpers
// -----------------------------------------------------------------------------
static void csv_emit_field(FILE* f, std::string_view s) {
    bool need_quote = false;
    for (char c : s) if (c==',' || c=='"' || c=='\n' || c=='\r') { need_quote = true; break; }
    if (!need_quote) { fwrite(s.data(), 1, s.size(), f); return; }
    fputc('"', f);
    for (char c : s) { if (c=='"') fputc('"', f); fputc(c, f); }
    fputc('"', f);
}

// -----------------------------------------------------------------------------
// Per-thread running mins (6 strings)
// -----------------------------------------------------------------------------
struct LocalMins {
    bool has[6] = {false,false,false,false,false,false};
    std::string vals[6];
    inline void update(int slot, std::string_view sv) {
        if (sv.empty()) return; // skip NULL (empty varlen)
        if (!has[slot]) { vals[slot].assign(sv.data(), sv.size()); has[slot] = true; }
        else if (std::string_view(vals[slot]) > sv) vals[slot].assign(sv.data(), sv.size());
    }
};

int main(int argc, char* argv[]) {
    GENDB_PHASE("total");

    if (argc < 3) {
        fprintf(stderr, "usage: %s <gendb_dir> <results_dir> [--params...]\n", argv[0]);
        return 2;
    }

    std::string gendb_dir = argv[1];
    std::string results_dir = argv[2];

    // Parameters
    int32_t prod_year_lo = (int32_t)parse_int_arg(argc, argv, "--production_year_lower", 2005);
    int32_t prod_year_hi = (int32_t)parse_int_arg(argc, argv, "--production_year_upper", 2008);
    double info_upper_d = parse_double_arg(argc, argv, "--info_upper", 3.0);
    std::string info_eq    = parse_string_arg(argc, argv, "--info_eq", "rating");
    std::string info_eq_2  = parse_string_arg(argc, argv, "--info_eq_2", "rating");
    std::string cc_eq      = parse_string_arg(argc, argv, "--country_code_eq", "[us]");

    // Build the "info < info_upper" lex-comparison threshold.
    // The SQL is `mi_idx2.info < '3.0'` lex. We accept either a numeric (3.0) or
    // the textual literal. Build a string form to lex-compare against.
    std::string info_upper_str;
    {
        // If user supplied the integer-ish value via CLI, render with one decimal so '<' '3.0' is consistent.
        char buf[64];
        if (info_upper_d == (double)(long long)info_upper_d)
            std::snprintf(buf, sizeof(buf), "%lld.0", (long long)info_upper_d);
        else
            std::snprintf(buf, sizeof(buf), "%g", info_upper_d);
        info_upper_str = buf;
    }
    std::string_view info_upper_sv(info_upper_str);

    fs::create_directories(results_dir);

    // -------------------------------------------------------------------------
    // mmap all required columns
    // -------------------------------------------------------------------------
    MM info_type_info_off, info_type_info_dat, info_type_id;
    MM kind_type_kind_off, kind_type_kind_dat, kind_type_id;
    MM link_type_link_off, link_type_link_dat, link_type_id;
    MM cn_cc_bin, cn_cc_dict_off, cn_cc_dict_dat, cn_id;
    MM cn_name_off, cn_name_dat;
    MM ml_movie_id, ml_linked_movie_id, ml_link_type_id;
    MM t_kind_id, t_prod_year, t_title_off, t_title_dat;
    MM mi_idx_info_type_id, mi_idx_info_off, mi_idx_info_dat;
    MM mc_company_id;
    MM mi_idx_movie_off_idx, mc_movie_off_idx;

    {
        GENDB_PHASE("data_loading");
        info_type_info_off.open(gendb_dir + "/info_type/info.off");
        info_type_info_dat.open(gendb_dir + "/info_type/info.dat");
        info_type_id.open(gendb_dir + "/info_type/id.bin");

        kind_type_kind_off.open(gendb_dir + "/kind_type/kind.off");
        kind_type_kind_dat.open(gendb_dir + "/kind_type/kind.dat");
        kind_type_id.open(gendb_dir + "/kind_type/id.bin");

        link_type_link_off.open(gendb_dir + "/link_type/link.off");
        link_type_link_dat.open(gendb_dir + "/link_type/link.dat");
        link_type_id.open(gendb_dir + "/link_type/id.bin");

        cn_cc_bin.open(gendb_dir + "/company_name/country_code.bin");
        cn_cc_dict_off.open(gendb_dir + "/company_name/country_code.dict.off");
        cn_cc_dict_dat.open(gendb_dir + "/company_name/country_code.dict.dat");
        cn_id.open(gendb_dir + "/company_name/id.bin");
        cn_name_off.open(gendb_dir + "/company_name/name.off");
        cn_name_dat.open(gendb_dir + "/company_name/name.dat");

        ml_movie_id.open(gendb_dir + "/movie_link/movie_id.bin");
        ml_linked_movie_id.open(gendb_dir + "/movie_link/linked_movie_id.bin");
        ml_link_type_id.open(gendb_dir + "/movie_link/link_type_id.bin");

        t_kind_id.open(gendb_dir + "/title/kind_id.bin");
        t_prod_year.open(gendb_dir + "/title/production_year.bin");
        t_title_off.open(gendb_dir + "/title/title.off");
        t_title_dat.open(gendb_dir + "/title/title.dat");

        mi_idx_info_type_id.open(gendb_dir + "/movie_info_idx/info_type_id.bin");
        mi_idx_info_off.open(gendb_dir + "/movie_info_idx/info.off");
        mi_idx_info_dat.open(gendb_dir + "/movie_info_idx/info.dat");

        mc_company_id.open(gendb_dir + "/movie_companies/company_id.bin");

        mi_idx_movie_off_idx.open(gendb_dir + "/_idx/movie_info_idx__movie_id__offsets.bin");
        mc_movie_off_idx.open(gendb_dir + "/_idx/movie_companies__movie_id__offsets.bin");
    }

    // -------------------------------------------------------------------------
    // Dimension literal resolution
    // -------------------------------------------------------------------------
    int32_t rating_id    = -1;
    int32_t tv_series_id = -1;
    int32_t link_type_id_set[8];
    int n_link = 0;
    int us_code = -1;

    {
        GENDB_PHASE("dim_resolve");
        // info_type.info = info_eq -> rating_id
        size_t ni = info_type_id.count<int32_t>();
        const int64_t* off = info_type_info_off.as<int64_t>();
        const char*    dat = info_type_info_dat.as<char>();
        const int32_t* ids = info_type_id.as<int32_t>();
        for (size_t r = 0; r < ni; ++r) {
            std::string_view sv(dat + off[r], (size_t)(off[r+1] - off[r]));
            if (sv == std::string_view(info_eq)) { rating_id = ids[r]; break; }
        }
        if (rating_id < 0) { fprintf(stderr, "info_type literal '%s' not found\n", info_eq.c_str()); return 3; }

        // kind_type.kind = 'tv series' -> tv_series_id
        size_t nk = kind_type_id.count<int32_t>();
        const int64_t* koff = kind_type_kind_off.as<int64_t>();
        const char*    kdat = kind_type_kind_dat.as<char>();
        const int32_t* kids = kind_type_id.as<int32_t>();
        std::string_view tv("tv series");
        for (size_t r = 0; r < nk; ++r) {
            std::string_view sv(kdat + koff[r], (size_t)(koff[r+1] - koff[r]));
            if (sv == tv) { tv_series_id = kids[r]; break; }
        }
        if (tv_series_id < 0) { fprintf(stderr, "kind_type 'tv series' not found\n"); return 3; }

        // link_type.link IN ('sequel','follows','followed by')
        size_t nl = link_type_id.count<int32_t>();
        const int64_t* loff = link_type_link_off.as<int64_t>();
        const char*    ldat = link_type_link_dat.as<char>();
        const int32_t* lids = link_type_id.as<int32_t>();
        std::string_view L1("sequel"), L2("follows"), L3("followed by");
        for (size_t r = 0; r < nl; ++r) {
            std::string_view sv(ldat + loff[r], (size_t)(loff[r+1] - loff[r]));
            if (sv == L1 || sv == L2 || sv == L3) {
                link_type_id_set[n_link++] = lids[r];
                if (n_link >= 8) break;
            }
        }
        if (n_link == 0) { fprintf(stderr, "no link_type matches\n"); return 3; }

        // country_code dict: find code for cc_eq.
        size_t nd = cn_cc_dict_off.count<int64_t>() - 1;  // K entries
        const int64_t* doff = cn_cc_dict_off.as<int64_t>();
        const char*    ddat = cn_cc_dict_dat.as<char>();
        for (size_t j = 0; j < nd; ++j) {
            std::string_view sv(ddat + doff[j], (size_t)(doff[j+1] - doff[j]));
            if (sv == std::string_view(cc_eq)) { us_code = (int)(j + 1); break; }
        }
        if (us_code < 0) { fprintf(stderr, "country_code '%s' not found\n", cc_eq.c_str()); return 3; }
    }

    // -------------------------------------------------------------------------
    // Build cn1_us_bitset[company_id] (id-1 = row, so just a flat bitmap over rows)
    // company_name.id is dense 1..N. We index by id (1..234997).
    // -------------------------------------------------------------------------
    const int32_t cn_n = (int32_t)cn_id.count<int32_t>();
    std::vector<uint8_t> cn_us_bitset((size_t)cn_n + 2, 0);
    {
        GENDB_PHASE("build_cn_us_bitset");
        const int16_t* cc = cn_cc_bin.as<int16_t>();
        const int32_t* ids = cn_id.as<int32_t>();
        int16_t target = (int16_t)us_code;
        for (int32_t r = 0; r < cn_n; ++r) {
            if (cc[r] == target) {
                int32_t id = ids[r];
                if (id > 0 && id <= cn_n) cn_us_bitset[(size_t)id] = 1;
            }
        }
    }

    // -------------------------------------------------------------------------
    // Main scan: morsel parallel over movie_link rows
    // -------------------------------------------------------------------------
    const int32_t ml_n = (int32_t)ml_movie_id.count<int32_t>();
    const int32_t title_n = (int32_t)t_kind_id.count<int32_t>();
    const int32_t* ml_mid = ml_movie_id.as<int32_t>();
    const int32_t* ml_lmid = ml_linked_movie_id.as<int32_t>();
    const int32_t* ml_lt = ml_link_type_id.as<int32_t>();
    const int32_t* t_kind = t_kind_id.as<int32_t>();
    const int32_t* t_year = t_prod_year.as<int32_t>();
    const int64_t* t_toff = t_title_off.as<int64_t>();
    const char*    t_tdat = t_title_dat.as<char>();
    const int32_t* mi_iti = mi_idx_info_type_id.as<int32_t>();
    const int64_t* mi_ioff = mi_idx_info_off.as<int64_t>();
    const char*    mi_idat = mi_idx_info_dat.as<char>();
    const int32_t* mc_cid = mc_company_id.as<int32_t>();
    const int64_t* cn_noff = cn_name_off.as<int64_t>();
    const char*    cn_ndat = cn_name_dat.as<char>();

    // Index files are int32[max_parent_id+2]. max_parent_id = 2528312 for title.
    const int32_t* mi_csr = mi_idx_movie_off_idx.as<int32_t>();
    const int32_t* mc_csr = mc_movie_off_idx.as<int32_t>();
    const int32_t csr_max_id = (int32_t)(mi_idx_movie_off_idx.bytes / 4) - 2; // == 2528312

    int max_threads = omp_get_max_threads();
    if (max_threads > 12) max_threads = 12;

    std::vector<LocalMins> per_thread(max_threads);

    {
        GENDB_PHASE("main_scan");
        #pragma omp parallel num_threads(max_threads)
        {
            int tid = omp_get_thread_num();
            LocalMins& L = per_thread[tid];

            #pragma omp for schedule(static, 2048)
            for (int32_t i = 0; i < ml_n; ++i) {
                // Cheapest filter first: link_type_id membership.
                int32_t ltid = ml_lt[i];
                bool ok = false;
                for (int k = 0; k < n_link; ++k) if (link_type_id_set[k] == ltid) { ok = true; break; }
                if (!ok) continue;

                int32_t t1_id = ml_mid[i];
                int32_t t2_id = ml_lmid[i];
                if (t1_id <= 0 || t1_id > title_n) continue;
                if (t2_id <= 0 || t2_id > title_n) continue;

                int32_t t1_row = t1_id - 1;
                int32_t t2_row = t2_id - 1;

                if (t_kind[t1_row] != tv_series_id) continue;
                if (t_kind[t2_row] != tv_series_id) continue;

                int32_t y2 = t_year[t2_row];
                if (y2 < prod_year_lo || y2 > prod_year_hi) continue;

                if (t1_id > csr_max_id || t2_id > csr_max_id) continue;

                // mi_idx2 probe (smaller selectivity due to info < '3.0'): t2 first
                std::string_view min_mi2;
                bool has_mi2 = false;
                {
                    int32_t lo = mi_csr[t2_id];
                    int32_t hi = mi_csr[t2_id + 1];
                    for (int32_t r = lo; r < hi; ++r) {
                        if (mi_iti[r] != rating_id) continue;
                        std::string_view sv(mi_idat + mi_ioff[r], (size_t)(mi_ioff[r+1] - mi_ioff[r]));
                        if (sv.empty()) continue;
                        if (!(sv < info_upper_sv)) continue;
                        if (!has_mi2 || sv < min_mi2) { min_mi2 = sv; has_mi2 = true; }
                    }
                }
                if (!has_mi2) continue;

                // mi_idx1 probe: t1, info_type_id == rating_id
                std::string_view min_mi1;
                bool has_mi1 = false;
                {
                    int32_t lo = mi_csr[t1_id];
                    int32_t hi = mi_csr[t1_id + 1];
                    for (int32_t r = lo; r < hi; ++r) {
                        if (mi_iti[r] != rating_id) continue;
                        std::string_view sv(mi_idat + mi_ioff[r], (size_t)(mi_ioff[r+1] - mi_ioff[r]));
                        if (sv.empty()) continue;
                        if (!has_mi1 || sv < min_mi1) { min_mi1 = sv; has_mi1 = true; }
                    }
                }
                if (!has_mi1) continue;

                // mc1 probe: t1, company_id in cn1_us_bitset
                std::string_view min_cn1;
                bool has_cn1 = false;
                {
                    int32_t lo = mc_csr[t1_id];
                    int32_t hi = mc_csr[t1_id + 1];
                    for (int32_t r = lo; r < hi; ++r) {
                        int32_t cid = mc_cid[r];
                        if (cid <= 0 || cid > cn_n) continue;
                        if (!cn_us_bitset[(size_t)cid]) continue;
                        // Read cn1.name at row (cid - 1)
                        int32_t cn_row = cid - 1;
                        std::string_view sv(cn_ndat + cn_noff[cn_row], (size_t)(cn_noff[cn_row+1] - cn_noff[cn_row]));
                        if (sv.empty()) continue;
                        if (!has_cn1 || sv < min_cn1) { min_cn1 = sv; has_cn1 = true; }
                    }
                }
                if (!has_cn1) continue;

                // mc2 probe: t2, any company
                std::string_view min_cn2;
                bool has_cn2 = false;
                {
                    int32_t lo = mc_csr[t2_id];
                    int32_t hi = mc_csr[t2_id + 1];
                    for (int32_t r = lo; r < hi; ++r) {
                        int32_t cid = mc_cid[r];
                        if (cid <= 0 || cid > cn_n) continue;
                        int32_t cn_row = cid - 1;
                        std::string_view sv(cn_ndat + cn_noff[cn_row], (size_t)(cn_noff[cn_row+1] - cn_noff[cn_row]));
                        if (sv.empty()) continue;
                        if (!has_cn2 || sv < min_cn2) { min_cn2 = sv; has_cn2 = true; }
                    }
                }
                if (!has_cn2) continue;

                // t1.title, t2.title
                std::string_view tt1(t_tdat + t_toff[t1_row], (size_t)(t_toff[t1_row+1] - t_toff[t1_row]));
                std::string_view tt2(t_tdat + t_toff[t2_row], (size_t)(t_toff[t2_row+1] - t_toff[t2_row]));

                // Fold into per-thread mins
                L.update(0, min_cn1);
                L.update(1, min_cn2);
                L.update(2, min_mi1);
                L.update(3, min_mi2);
                L.update(4, tt1);
                L.update(5, tt2);
            }
        }
    }

    // Global reduction across threads
    LocalMins G;
    for (int t = 0; t < max_threads; ++t) {
        for (int s = 0; s < 6; ++s) {
            if (per_thread[t].has[s]) G.update(s, per_thread[t].vals[s]);
        }
    }

    // -------------------------------------------------------------------------
    // Output CSV
    // -------------------------------------------------------------------------
    {
        GENDB_PHASE("output");
        std::string out_path = results_dir + "/Q33a.csv";
        FILE* f = std::fopen(out_path.c_str(), "wb");
        if (!f) { fprintf(stderr, "cannot open %s\n", out_path.c_str()); return 4; }
        std::fprintf(f, "first_company,second_company,first_rating,second_rating,first_movie,second_movie\n");
        for (int s = 0; s < 6; ++s) {
            if (s) fputc(',', f);
            if (G.has[s]) csv_emit_field(f, G.vals[s]);
        }
        fputc('\n', f);
        std::fclose(f);
    }

    return 0;
}
