// Q20c — IMDB JOB
// Generated by GenDB code-gen agent.

#include <cstdio>
#include <cstdint>
#include <cstring>
#include <climits>
#include <string>
#include <vector>
#include <atomic>
#include <algorithm>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include <omp.h>

#include "timing_utils.h"
#include "mmap_utils.h"
#include "cli_params.h"

using gendb::MmapColumn;

static inline bool memmem_q(const char* hay, size_t hlen, const char* needle, size_t nlen) {
    if (nlen == 0) return true;
    if (hlen < nlen) return false;
    return memmem(hay, hlen, needle, nlen) != nullptr;
}

static void ensure_dir(const std::string& p) {
    mkdir(p.c_str(), 0755);
}

// Compare two byte strings lexicographically (memcmp then length tiebreak).
static inline int cmp_bytes(const char* a, size_t la, const char* b, size_t lb) {
    size_t m = la < lb ? la : lb;
    int c = std::memcmp(a, b, m);
    if (c != 0) return c;
    if (la == lb) return 0;
    return la < lb ? -1 : 1;
}

int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::fprintf(stderr, "Usage: %s <gendb_dir> <results_dir> [--param value ...]\n", argv[0]);
        return 1;
    }
    std::string gendb_dir = argv[1];
    std::string results_dir = argv[2];
    ensure_dir(results_dir);

    GENDB_PHASE("total");

    // --- Open all columns / indexes via mmap ---
    // comp_cast_type
    MmapColumn<int32_t> cct_id;
    MmapColumn<int64_t> cct_kind_off;
    MmapColumn<char>    cct_kind_dat;
    // kind_type
    MmapColumn<int32_t> kt_id;
    MmapColumn<int64_t> kt_kind_off;
    MmapColumn<char>    kt_kind_dat;
    // keyword
    MmapColumn<int32_t> kw_id;
    MmapColumn<int64_t> kw_keyword_off;
    MmapColumn<char>    kw_keyword_dat;
    // complete_cast
    MmapColumn<int32_t> cc_movie_id;
    MmapColumn<int32_t> cc_subject_id;
    MmapColumn<int32_t> cc_status_id;
    // title
    MmapColumn<int32_t> t_kind_id;
    MmapColumn<int32_t> t_production_year;
    MmapColumn<int64_t> t_title_off;
    MmapColumn<char>    t_title_dat;
    // movie_keyword
    MmapColumn<int32_t> mk_keyword_id;
    MmapColumn<int32_t> mk_off; // movie_id offsets index
    // char_name
    MmapColumn<int64_t> chn_name_off;
    MmapColumn<char>    chn_name_dat;
    // cast_info
    MmapColumn<int32_t> ci_person_id;
    MmapColumn<int32_t> ci_person_role_id;
    MmapColumn<int32_t> ci_off; // movie_id offsets index
    // name
    MmapColumn<int64_t> n_name_off;
    MmapColumn<char>    n_name_dat;

    {
        GENDB_PHASE("data_loading");
        cct_id.open(gendb_dir + "/comp_cast_type/id.bin");
        cct_kind_off.open(gendb_dir + "/comp_cast_type/kind.off");
        cct_kind_dat.open(gendb_dir + "/comp_cast_type/kind.dat");

        kt_id.open(gendb_dir + "/kind_type/id.bin");
        kt_kind_off.open(gendb_dir + "/kind_type/kind.off");
        kt_kind_dat.open(gendb_dir + "/kind_type/kind.dat");

        kw_id.open(gendb_dir + "/keyword/id.bin");
        kw_keyword_off.open(gendb_dir + "/keyword/keyword.off");
        kw_keyword_dat.open(gendb_dir + "/keyword/keyword.dat");

        cc_movie_id.open(gendb_dir + "/complete_cast/movie_id.bin");
        cc_subject_id.open(gendb_dir + "/complete_cast/subject_id.bin");
        cc_status_id.open(gendb_dir + "/complete_cast/status_id.bin");

        t_kind_id.open(gendb_dir + "/title/kind_id.bin");
        t_production_year.open(gendb_dir + "/title/production_year.bin");
        t_title_off.open(gendb_dir + "/title/title.off");
        t_title_dat.open(gendb_dir + "/title/title.dat");

        mk_keyword_id.open(gendb_dir + "/movie_keyword/keyword_id.bin");
        mk_off.open(gendb_dir + "/_idx/movie_keyword__movie_id__offsets.bin");

        chn_name_off.open(gendb_dir + "/char_name/name.off");
        chn_name_dat.open(gendb_dir + "/char_name/name.dat");

        ci_person_id.open(gendb_dir + "/cast_info/person_id.bin");
        ci_person_role_id.open(gendb_dir + "/cast_info/person_role_id.bin");
        ci_off.open(gendb_dir + "/_idx/cast_info__movie_id__offsets.bin");

        n_name_off.open(gendb_dir + "/name/name.off");
        n_name_dat.open(gendb_dir + "/name/name.dat");

        // Hint kernel about access patterns
        chn_name_dat.advise_sequential();
        ci_person_id.advise_random();
        ci_person_role_id.advise_random();
    }

    // --- Resolve dims ---
    int32_t cct1_id = -1;          // 'cast'
    int32_t cct2_a = -1, cct2_b = -1; // up to 2 ids matching %complete%
    int cct2_count = 0;
    int32_t kt_movie = -1;
    std::vector<int32_t> K_ids;
    K_ids.reserve(10);

    {
        GENDB_PHASE("resolve_dims");
        // comp_cast_type
        for (size_t i = 0; i < cct_id.size(); ++i) {
            int64_t s = cct_kind_off[i], e = cct_kind_off[i+1];
            const char* p = cct_kind_dat.data + s;
            size_t l = (size_t)(e - s);
            if (l == 4 && std::memcmp(p, "cast", 4) == 0) {
                cct1_id = cct_id[i];
            }
            if (memmem_q(p, l, "complete", 8)) {
                if (cct2_count == 0) cct2_a = cct_id[i];
                else if (cct2_count == 1) cct2_b = cct_id[i];
                cct2_count++;
            }
        }
        // kind_type
        for (size_t i = 0; i < kt_id.size(); ++i) {
            int64_t s = kt_kind_off[i], e = kt_kind_off[i+1];
            size_t l = (size_t)(e - s);
            if (l == 5 && std::memcmp(kt_kind_dat.data + s, "movie", 5) == 0) {
                kt_movie = kt_id[i];
                break;
            }
        }
        // keyword
        static const char* KW_LIST[] = {
            "superhero", "marvel-comics", "based-on-comic", "tv-special",
            "fight", "violence", "magnet", "web", "claw", "laser"
        };
        static const size_t KW_LEN[] = {9, 13, 14, 10, 5, 8, 6, 3, 4, 5};
        const int NK = sizeof(KW_LIST) / sizeof(KW_LIST[0]);
        for (size_t i = 0; i < kw_id.size(); ++i) {
            int64_t s = kw_keyword_off[i], e = kw_keyword_off[i+1];
            size_t l = (size_t)(e - s);
            const char* p = kw_keyword_dat.data + s;
            for (int j = 0; j < NK; ++j) {
                if (l == KW_LEN[j] && std::memcmp(p, KW_LIST[j], l) == 0) {
                    K_ids.push_back(kw_id[i]);
                    break;
                }
            }
            if ((int)K_ids.size() == NK) break;
        }
    }

    if (cct1_id < 0 || cct2_count == 0 || kt_movie < 0 || K_ids.empty()) {
        std::fprintf(stderr, "[Q20c] failed to resolve dims: cct1=%d cct2_count=%d kt_movie=%d kids=%zu\n",
                     cct1_id, cct2_count, kt_movie, K_ids.size());
    }

    // --- Scan complete_cast: build M_cc (deduped movie_ids) ---
    std::vector<int32_t> M_cc;
    M_cc.reserve(8192);
    const size_t TITLE_ROWS = t_kind_id.size(); // 2528312
    std::vector<uint8_t> seen(TITLE_ROWS + 2, 0); // bitset-by-byte for dedup; mv 1..N

    {
        GENDB_PHASE("scan_complete_cast");
        const size_t N = cc_movie_id.size();
        const int32_t s1 = cct1_id;
        const int32_t ca = cct2_a, cb = cct2_b;
        const bool have_b = (cct2_count >= 2);
        for (size_t r = 0; r < N; ++r) {
            int32_t sid = cc_subject_id[r];
            if (sid != s1) continue;
            int32_t st = cc_status_id[r];
            if (!(st == ca || (have_b && st == cb))) continue;
            int32_t mv = cc_movie_id[r];
            if (mv == INT32_MIN) continue;
            if ((size_t)mv > TITLE_ROWS) continue;
            if (seen[mv]) continue;
            seen[mv] = 1;
            M_cc.push_back(mv);
        }
    }

    // --- Filter by title (kind_id, production_year) ---
    {
        GENDB_PHASE("filter_title");
        std::vector<int32_t> next;
        next.reserve(M_cc.size());
        for (int32_t mv : M_cc) {
            size_t row = (size_t)mv - 1;
            if (t_kind_id[row] != kt_movie) continue;
            int32_t py = t_production_year[row];
            if (py == INT32_MIN || py <= 2000) continue;
            next.push_back(mv);
        }
        M_cc.swap(next);
    }

    // --- Filter by movie_keyword existence (K_ids small set) ---
    {
        GENDB_PHASE("filter_movie_keyword");
        std::vector<int32_t> next;
        next.reserve(M_cc.size());
        const int NK = (int)K_ids.size();
        const int32_t* kids = K_ids.data();
        for (int32_t mv : M_cc) {
            int32_t lo = mk_off[mv];
            int32_t hi = mk_off[mv + 1];
            bool ok = false;
            for (int32_t r = lo; r < hi && !ok; ++r) {
                int32_t kid = mk_keyword_id[r];
                for (int j = 0; j < NK; ++j) {
                    if (kid == kids[j]) { ok = true; break; }
                }
            }
            if (ok) next.push_back(mv);
        }
        M_cc.swap(next);
    }

    // --- Build chn_bitset: char_name.name IS NOT NULL AND (%man% OR %Man%) ---
    const size_t CHN_ROWS = chn_name_off.size() - 1; // 3140339
    std::vector<uint8_t> chn_bs(CHN_ROWS + 2, 0); // index by chn.id (1..N)

    {
        GENDB_PHASE("build_chn_bitset");
        const int64_t* off = chn_name_off.data;
        const char* dat = chn_name_dat.data;
        uint8_t* bs = chn_bs.data();
        #pragma omp parallel for schedule(static)
        for (size_t i = 0; i < CHN_ROWS; ++i) {
            int64_t s = off[i], e = off[i+1];
            if (e <= s) continue; // NULL (empty)
            size_t l = (size_t)(e - s);
            const char* p = dat + s;
            // case-sensitive %man% OR %Man%
            if (memmem_q(p, l, "man", 3) || memmem_q(p, l, "Man", 3)) {
                bs[i + 1] = 1; // chn.id = i+1 (dense)
            }
        }
    }

    // --- Probe cast_info per mv; aggregate MIN(n.name), MIN(t.title) ---
    // Thread-local min holders, reduce at end.
    int nthreads = 1;
    #ifdef _OPENMP
    nthreads = omp_get_max_threads();
    #endif

    // Per-thread: min_name_ptr/len, min_title_ptr/len
    std::vector<const char*> tmin_name_p(nthreads, nullptr);
    std::vector<size_t>      tmin_name_l(nthreads, 0);
    std::vector<const char*> tmin_title_p(nthreads, nullptr);
    std::vector<size_t>      tmin_title_l(nthreads, 0);

    {
        GENDB_PHASE("probe_cast_info");
        const int32_t* off_ci = ci_off.data;
        const int32_t* prid_arr = ci_person_role_id.data;
        const int32_t* pid_arr = ci_person_id.data;
        const uint8_t* bs = chn_bs.data();
        const int64_t* nn_off = n_name_off.data;
        const char* nn_dat = n_name_dat.data;
        const int64_t* tt_off = t_title_off.data;
        const char* tt_dat = t_title_dat.data;
        const size_t N_NAME = n_name_off.size() - 1;

        const size_t MV_N = M_cc.size();
        const int32_t* MV = M_cc.data();

        #pragma omp parallel
        {
            int tid = 0;
            #ifdef _OPENMP
            tid = omp_get_thread_num();
            #endif
            const char* lmin_name_p = nullptr; size_t lmin_name_l = 0;
            const char* lmin_title_p = nullptr; size_t lmin_title_l = 0;

            #pragma omp for schedule(dynamic, 64)
            for (size_t mi = 0; mi < MV_N; ++mi) {
                int32_t mv = MV[mi];
                int32_t lo = off_ci[mv];
                int32_t hi = off_ci[mv + 1];
                bool hit_in_mv = false;
                for (int32_t r = lo; r < hi; ++r) {
                    int32_t prid = prid_arr[r];
                    if (prid == INT32_MIN) continue;
                    if ((size_t)prid == 0 || (size_t)prid > CHN_ROWS) continue;
                    if (!bs[prid]) continue;
                    int32_t pid = pid_arr[r];
                    if (pid == INT32_MIN) continue;
                    if ((size_t)pid == 0 || (size_t)pid > N_NAME) continue;
                    // update min name
                    int64_t ns = nn_off[pid - 1], ne = nn_off[pid];
                    size_t nl = (size_t)(ne - ns);
                    if (nl == 0) continue; // NULL name
                    const char* np = nn_dat + ns;
                    if (lmin_name_p == nullptr ||
                        cmp_bytes(np, nl, lmin_name_p, lmin_name_l) < 0) {
                        lmin_name_p = np;
                        lmin_name_l = nl;
                    }
                    hit_in_mv = true;
                }
                if (hit_in_mv) {
                    int64_t ts = tt_off[mv - 1], te = tt_off[mv];
                    size_t tl = (size_t)(te - ts);
                    if (tl > 0) {
                        const char* tp = tt_dat + ts;
                        if (lmin_title_p == nullptr ||
                            cmp_bytes(tp, tl, lmin_title_p, lmin_title_l) < 0) {
                            lmin_title_p = tp;
                            lmin_title_l = tl;
                        }
                    }
                }
            }

            tmin_name_p[tid] = lmin_name_p;
            tmin_name_l[tid] = lmin_name_l;
            tmin_title_p[tid] = lmin_title_p;
            tmin_title_l[tid] = lmin_title_l;
        }
    }

    // Reduce
    const char* min_name_p = nullptr; size_t min_name_l = 0;
    const char* min_title_p = nullptr; size_t min_title_l = 0;
    for (int t = 0; t < nthreads; ++t) {
        if (tmin_name_p[t] != nullptr) {
            if (min_name_p == nullptr ||
                cmp_bytes(tmin_name_p[t], tmin_name_l[t], min_name_p, min_name_l) < 0) {
                min_name_p = tmin_name_p[t];
                min_name_l = tmin_name_l[t];
            }
        }
        if (tmin_title_p[t] != nullptr) {
            if (min_title_p == nullptr ||
                cmp_bytes(tmin_title_p[t], tmin_title_l[t], min_title_p, min_title_l) < 0) {
                min_title_p = tmin_title_p[t];
                min_title_l = tmin_title_l[t];
            }
        }
    }

    // --- main_scan phase end (we tag it logically as a no-op since the heavy work was probe_cast_info) ---
    { GENDB_PHASE("main_scan"); /* sentinel */ }

    // --- Output ---
    {
        GENDB_PHASE("output");
        std::string out_path = results_dir + "/Q20c.csv";
        FILE* f = std::fopen(out_path.c_str(), "w");
        if (!f) {
            std::fprintf(stderr, "cannot open %s\n", out_path.c_str());
            return 2;
        }
        std::fprintf(f, "cast_member,complete_dynamic_hero_movie\n");

        auto write_field = [&](const char* p, size_t l) {
            bool need_quote = false;
            for (size_t i = 0; i < l; ++i) {
                char c = p[i];
                if (c == ',' || c == '"' || c == '\n' || c == '\r') { need_quote = true; break; }
            }
            if (!need_quote) {
                std::fwrite(p, 1, l, f);
            } else {
                std::fputc('"', f);
                for (size_t i = 0; i < l; ++i) {
                    char c = p[i];
                    if (c == '"') std::fputc('"', f);
                    std::fputc(c, f);
                }
                std::fputc('"', f);
            }
        };

        if (min_name_p && min_title_p) {
            write_field(min_name_p, min_name_l);
            std::fputc(',', f);
            write_field(min_title_p, min_title_l);
            std::fputc('\n', f);
        }
        std::fclose(f);
    }

    return 0;
}
